### ISSUE TITLE
Hanging queries for "hanging" mongos proxy

### ISSUE THREAD

**Issue by geronime** [christkv/mongodb-core#108]
With one of my projects we repeatedly experienced an issue with hanging queries whenever a specific network partitioning happened; resulting in hanging (but not closed!) sockets. The project is hosted on public cloud and we've experienced the issue repeatedly so I'd assume somebody else must have run into the same hiccup.

Our goal was to be able to detect this sort of event and instead of having "hanging" requests (caused by underlying hanging mongodb queries) to immediately respond with an error from the app. We did not want to explicitly time each mongo query out, not only because the project is quite large and it would be a considerable development effort. We'd prefer having some system solution that would be able to recognise the hanging state and disconnect the troubled proxy. After all the application shouldn't have to handle something that could seem more of a driver's job.

We figured out a dirty way to **simulate the issue**:
* have a small cluster set up with several mongos proxies involved
* have a simple [test script](https://gist.github.com/geronime/a0362e6d02af74c88e927abaef286b9e) running
* send SIGSTOP to one of the mongos
* as a result queries start to hang
* after sending SIGCONT the queries resume, only they took as long as the mongos process was asleep

Close enough to the real-live partitioned network scenario. We found out:
* `mongos.connectOptions.socketTimeoutMS` doesn't help if there is sufficient traffic on the app
* using `maxTimeMS` also doesn't help as this times a query out on server side as far as I understand and it never gets to the server during the hanging state
* the keep-alive is not helpful at all as the default keep-alive settings are completely unsuitable for this use, we don't want to configure them on system level and there is no way to configure them through the driver as Node.js socket actually [doesn't support](https://github.com/nodejs/node/issues/4048) it so far

**The workaround**:
In the initial workaround, where we've been using mongoose, we introduced regular pings in combination with `db.bufferMaxEntries:0`. Each iteration we issued as many pings as the driver had connections in the pool, timing the whole bulk of parallel pings out. Whenever a timeout hit we just forcefully closed the mongoose connection, making mongoose an automatic reconnection for us.
This workaround has a few downsides:
* the whole connection is dropped and reconnected instead of disconnecting just the troubled proxy
* issuing as many pings as all connections across all mongos proxies is a bit overkill - it is enough to ping just once per mongos; whenever the connection is stale, all of the connections in that particular proxy's pool behave the same way

Recently we've been moving some parts of the app to use the mongodb driver instead of mongoose and therefore we had to come up with some non-mongoose solution, favourably without monkey-patching in every part of the app that is connecting to the database.

I noticed that mongodb 2.1.x behaves a bit weird: I can see occasional reconnections of individual pool connections. This isn't just a result of the default `socketTimeoutMS=120000` that was introduced. I haven't looked deeper; in mongos logs I can see the test script dropping the connection and reconnecting later. With 2.0 this is not the case. mongodb@2.0 is using mongodb-core@1.2.

**Solution?**
I [forked](https://github.com/geronime/mongodb-core) mongodb-core and implemented custom keep-alive utilising pings - [diff against V1.2.32](https://github.com/geronime/mongodb-core/compare/V1.2.32...1.2.32_mongos_ping). I don't think this is an ideal solution as I haven't dug deep enough into the driver and it definitely could use some functional test simulation first. I'd be glad if you looked at it and gave me your feedback - perhaps, after some iterations, it would make sense to include something like this into the core driver or implement something else whatsoever to deal with the issue. 
The extra mongos options would have to be propagated to the mongodb driver as well, for testing you can just uncomment the [appropriate line](https://github.com/geronime/mongodb-core/commit/0569f5d698221d3f5b066da15a62cfdda886fe98#diff-934e557209bbdb06743917230f540f3aR312).

Sorry for such a long article. :-)

**Comment by christkv** [comment]
I just released the 2.2.x branch of the driver, please let me know if the problem still persists.

**Comment by geronime** [comment]
Quick test shows unchanged behaviour. Whenever I send one of the mongos SIGSTOP all the queries going to that proxy hang as well.
I believe this specific kind of issue hasn't been addressed in the driver until now.

**Comment by christkv** [comment]
They would hang until there is a socket timeout. that's expected behavior. The driver will then try to reconnect and all queries hand until there is a reconnect event.

**Comment by geronime** [comment]
It should. I haven't had a chance to test this with the real situation; with the described simulation the `socketTimeoutMS` doesn't happen in case of sufficient traffic from the app. My understanding was that there were new queries issued on the hanging connection thus keeping the socket "alive". Initially the `socketTimeoutMS` was our first attempt to deal with the issue; in the end we settled with the ping-based workaround I described above. You can also refer to [CS-26144](https://jira.mongodb.org/browse/CS-26144).

**Comment by christkv** [comment]
If node itself does not notify the driver that the connection is dead there really is no way for the driver to know that connection is dead and thus remove it from the pool.

**Comment by geronime** [comment]
Not directly. It can however try to test its connections periodically using timed-out pings and after certain consecutively failed pings deem the connection stale and force that particular proxy to reconnect. That's what I tried to achieve in [V1.2.32.p0](https://github.com/geronime/mongodb-core/compare/V1.2.32...1.2.32_mongos_ping). The `customKeepAlive` option enables such checking in the `mongosInquirer` and so far my testing shows that it solves the described issue.

**Comment by christkv** [comment]
The 2.0 branch of the mongodb-core driver (mongodb driver 2.2.1 or higher) does do monitoring by calling ismaster. However your fix is kind of circumventing how sockets should work. Writing to a socket that is just sending tcp packets into limbo should eventually socketTimeout anyway as there are no replies.

Are you trying to simulate a firewall here ?

**Comment by geronime** [comment]
No, I'm trying to simulate the real keep-alive, that is not yet properly configurable on process level through node - [more here](https://github.com/nodejs/node/issues/4048). The default keep-alive options are completely unsuitable (I believe the default linux TCP keep alive options are "issue first keep alive check after two hours of inactivity, try every 75 seconds and mark the connection as broken after 9 failed checks") and it is generally undesirable to modify these settings on system level as it affects all processes utilising keep-alive.
I'm not sending the ping on particular socket, merely just particular mongos proxy.
"eventually socketTimeout anyway" is simply too long if that happens at all.

**Comment by christkv** [comment]
My suggestion is setting a short connect timeout as well as socket timeout this would any new attempts at connection creation will fail fast and any outstanding connections will aswell.

The right thing to do is to open a ticket on libuv itself to fix this.

**Comment by geronime** [comment]
We already use `connectTimeoutMS:1000` and as I pointed out `socketTimeoutMS` doesn't have the expected effect. On top of that in case of inactivity `socketTimeoutMS` then reconnects all the inactive connections even though it may not be really needed.
That's why I implemented the synthetic keep alive using **timed-out** pings directly in the mongosInquirer and it seems to do just the right thing. We thought to offer it here so that other people may benefit from the feature, if they choose to enable it.
I also pointed out that with 2.1 version of the mongodb driver I see unexpected reconnections from the driver (not just caused by the newly introduced default `socketTimeoutMS:120000`) so we chose to stick with 2.0 for now and implemented the synthetic keep alive check against used mongodb-core version.
Opening a ticket on libuv itself seems like the right thing to do. I believe it will take a long time before and if it actually gets to Node.js and maybe then to the mongodb driver.
Feel free to close this issue; we can stick with the modified version.

**Comment by christkv** [comment]
you might want to still use the 2.2 driver instead as it's a complete refactoring and that will future proof you for 3.4 as it also will contain support for the new Decimal type.

**Comment by christkv** [comment]
Here are two other possible ideas you could try.

- Always close the proxy object if there is a timeout (forcing a full reconnect to happen and thus it never returning to the set until it's fixed)
- Getting all the sockets (connections) and using this package to enable working keepalive https://www.npmjs.com/package/net-keepalive

**Comment by geronime** [comment]
Would it actually make sense to implement the net-keepalive into the driver?

**Comment by christkv** [comment]
unfortunately no as it does not cover any other os than linux

**Comment by christkv** [comment]
have a look at https://github.com/christkv/mongodb-core/commit/6dc3c1d18bda6f0016d76ea7a3bd175a4348e0e8 it might be what you are looking for. You can test this by just using the 2.2 branch of the mongodb driver as it's pulling mongodb-core from the 2.0 branch for development.

**Comment by geronime** [comment]
this might do the trick. I'll test that later.

**Comment by christkv** [comment]
closed due to inaction
