### ISSUE TITLE
Standarizing mongoErrors and its API

### ISSUE THREAD

**Issue by diervo** [christkv/mongodb-core#11]
I file this since in the documentation there is no mention to the shape/api of MongoError object, and I think it will be an interesting "contract" to have :)

In error.js the contructor has name, message and stack:
```
function MongoError(message) {
  this.name = 'MongoError';
  this.message = message;
  this.stack = (new Error()).stack;
}
```
Bun when the driver throws an error it has mostly a different shape, like:
```
finalResult.writeErrors.push({
            index: i
          , code: result.code
          , errmsg: result.errmsg || result.err || result.errMsg
```

It will be nice to have it documented and consolidated, so that we can rely on a contract API to build services on top.

Let me know if this makes sense.

**Comment by christkv** [comment]
ah that's because it's actually not an error but an emulation of the 2.6 write command results.

**Comment by christophehurpeau** [comment]
Maybe you should use `Error.captureStackTrace(this, MongoError);` instead of (new Error()).stack ?

[https://iojs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt](https://iojs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt)

**Comment by owenallenaz** [comment]
Out of coincidence, I just had that change pulled in recently. #14
