### ISSUE TITLE
Version 2.0.3 of mongodb-core npm package has problems connecting to healthy replica set

### ISSUE THREAD

**Issue by danielsan** [christkv/mongodb-core#111]
I've created a tiny project instructing how to reproduce the bug.

Version 1.3.21 works fine
https://github.com/danielsan/mongodb-core-replset-bug/tree/1.3.21

But 2.0.3 does not
https://github.com/danielsan/mongodb-core-replset-bug/tree/2.0.3

**Comment by shaharmor** [comment]
This is a critical issue, any chance to get it fixed ASAP?

**Comment by christkv** [comment]
fixed in 2.0.4 and released under mongodb 2.2.1

**Comment by danielsan** [comment]
Thanks guys
