### ISSUE TITLE
v1.3.21: reconnect logic with pool opens exponentially more connections with each retry 

### ISSUE THREAD

**Issue by yuzeh** [christkv/mongodb-core#112]
Hi,

I've been trying to simulate network disruption scenarios on node-mongodb-native v2.1.21 (which looks like it uses mongodb-core v1.3.21).

The way I'm simulating this is by running the node client on my local machine and turning off the internet.

When I make a MongoClient with reconnectTries=3000 and reconnectInterval=2000, I notice that, after the initial timeout, the connection pool will create more connections with each retry (e.g. 3 connections at 2s, 6 connections at 4s, 10 connections at 6s, 15 connections at 8s, etc.). I've been able to divine this happening by looking at debug logs:

https://gist.github.com/yuzeh/4b099411672e4ee0209579dfde0285fc

What's going on here? Is this expected behavior?

Dan

**Comment by christkv** [comment]
you want to try the 2.2.x branch of the driver

**Comment by christkv** [comment]
you should upgrade to 2.2.4 as timeouts in 2.2.2 or earlier can cause connection growth.
