### ISSUE TITLE
"no mongos proxies found in seed list" error after upgrade

### ISSUE THREAD

**Issue by garrows** [christkv/mongodb-core#118]
Hi,

We are using node-mongodb-native and since upgrading to the latest version a couple of days ago we are getting the error `"no mongos proxies found in seed list"` which was introduced in mongodb-core 7 days ago https://github.com/christkv/mongodb-core/blame/2.0/lib/topologies/mongos.js#L304

Looks to be related to https://jira.mongodb.org/browse/NODE-764

We are passing the replica set information in the options like so

```
mongoose.connect( connectionString, { replSet: setName: 'some-name', ssl: true, sslValidate: true } )`
```

The issue goes away when we use the options in the connection string instead like so
```
mongoose.connect( connectionString + 'replicaSet=some-name;ssl=true;sslValidate=true',  )`
```

Thanks in advance.

**Comment by christkv** [comment]
Hi, yes this is caused by the a change in 2.2.x that speeds up connections by a factor of 2x for replicasets. There is no parameter called setName. It's called replicaSet. The reason it still worked was due to a bug (feature) of 2.1 and 2.0 where it would still connect correctly. You can specify the connection in two ways.

```js
mongoose.connect( connectionString, { replSet: {
  replicaSet: 'some-name', ssl: true, sslValidate: true 
}} )`
```

or as you did using the url string. I'm working on adding better warning messages so it will be easier for people to understand what is going on.

**Comment by ycheapopo** [comment]
I get this error on mongodb-croe 2.0.11,
 when connection string was not using any replication set

**Comment by christkv** [comment]
That is expected behavior replicaset name must be provided so the driver knows which replicaset it is connected to. Previous versions allowed for "auto" connect to the first found replicaset but this is considered a bug.

**Comment by ycheapopo** [comment]
Even after defining a replica set (with only 1 member) issue still occurs.
The machine I am running on is : 
windows server 2012 R2 VM (running in azure),  
mongoose 4.6.0
mongodb 2.2.9
mongodb-core 2.0.11

connection string:
mongodb://[machinename]:[port]/[db]?replicaSet=[replicatesetname]
issue happen also when i configure the options parameter, as you instructed (apart from setting  ssl to false)

**Comment by christkv** [comment]
mongoose does it's own uri parsing so might be an issue on their side, try it with the mongodb driver only

**Comment by ycheapopo** [comment]
Indeed, creating a small standalone connection with mongodb without mongoose works.
Thank you very much for your prompt assistance.
