### ISSUE TITLE
remove mkdirp and rimraf dependencies

### ISSUE THREAD

**Issue by kaizhu256** [christkv/mongodb-core#12]
i don't see any usage for these modules in the source code.

since this is a 'lite' package intended to remove as much bloat as possible, i suggest removing these modules.  u can add them back in when the use-case has 'materialized' in code.

p.s. it is not too hard to write mkdirp (or whatever u want in rimraf) in pure node (and it can be synchronous io, since the use-case is almost always during startup / exit). e.g.

```
               function mkdirpSync (dir) {
                /*
                    this function will create the dir, and parent dir if needed
                */
                try {
                    require('fs').mkdirSync(dir);
                } catch (errorCaught) {
                    // recursively create parent dir
                    if (errorCaught.code === 'ENOENT') {
                        mkdirpSync(require('path').dirname(dir));
                        mkdirpSync(dir);
                    }
                }
```

**Comment by christkv** [comment]
moved to dev dependencies

**Comment by kaizhu256** [comment]
thx!
