### ISSUE TITLE
Queries buffering forever during replicaSet instability

### ISSUE THREAD

**Issue by owenallenaz** [christkv/mongodb-core#123]
Could you clarify a little bit more about the design intent behind the fail over mechanics within the driver. Right now if I perform a query to a replicaSet and there is no server that can perform that query (whatever the writeConcern is), then the query is put into a store effectively forever, until the driver is then able to run that query.

1. In order for that buffer to be cleared it requires `replicaSetState.hasPrimaryAndSecondary()` to be true. Well, if a query came in and the primary was not available, it gets put into the store. Then once the primary becomes available, why is the query not executed? It would seem to be me that the process of `store.execute()` has to take into account the intent of the query. If the query is meant for a secondary, and there is a secondary, it should run. If there is a primary and it's to the primary, it should run. Once the primary comes online, NEW queries will run, but the buffered queries do not until a secondary comes online. This is not functioning due to the reliance of `hasPrimaryAndSecondary()` in cases where the secondary OR primary is not required.

2. Currently that buffer in `store` fills forever. It seems to me that even utilizing that store should be optional or at least governed by settings. In example, there could be a setting for the max number of queries that can fill that store. And/or a setting for a timeout for queries within that store. In our application we would rather return an error immediately if there is no primary, but I could see how others would maybe prefer to wait a set period of time before those queries return while waiting for a replSet fail-over.

As usual I'd be willing to do a pull request to get some of these things ironed out if there is interest.

**Comment by christkv** [comment]
The commit will sort out point 1 from the perspective mongodb-core. Point two has been covered for ages in the mongodb driver (where the store itself lives). You can set **bufferMaxEntries** to control the number of operation in the store.
