### ISSUE TITLE
Different domain behavior in versions 2.x (1.3.21 to 2.0.7)

### ISSUE THREAD

**Issue by iamdoron** [christkv/mongodb-core#124]
There is a different behavior in the way domain-binding works in version v2

Run the following code using v2.0.7 & v1.3.21 - you'll get different results

```javascript
const Server = require('mongodb-core').Server;
const Domain = require('domain');

const server = new Server({
    host: 'localhost'
  , port: 27017
  , reconnect: true
  , reconnectInterval: 50
});

const serverConnectDomain = Domain.createDomain();
serverConnectDomain.title = "serverConnectDomain";
serverConnectDomain.enter();
server.connect();
serverConnectDomain.exit();

server.on('connect', function(_server) {

  console.log(process.domain.title);
  const commandDomain = Domain.createDomain();
  commandDomain.title = "commandDomain";
  commandDomain.enter();
  server.command('system.$cmd', {ismaster: true}, function(err, result) {
    
    console.log(process.domain.title);
  })
  commandDomain.exit();
});
```

v1.3.21 output (what I expected):
```
serverConnectDomain
commandDomain
```

v2.0.7 output:
```
serverConnectDomain
serverConnectDomain
```

I know the domain module is [pending deprecation](https://nodejs.org/api/domain.html#domain_domain), I use it for testing (via test runner that catches domain errors when wrong asserts are made)

**Comment by owenallenaz** [comment]
Does this still occur if you pass the `domainsEnabled: true` setting? I added basic domain support in a pull request a week ago and there's a chance it resolves your issue. I did it to the main query pathway on Pool.prototype.write() so there is a chance the authentication systems or connect systems are utilizing it properly, but try it out and see.

**Comment by iamdoron** [comment]
@owenallenaz - yes it works as expected
