### ISSUE TITLE
Error while doing geo queries

### ISSUE THREAD

**Issue by svenvarkel** [christkv/mongodb-core#125]
I'm trying to run geo queries with $near etc. I get errors like that and it's impossible to get any geo queries work.
The collections are properly indexed with 2dsphere index. All geo queries work fine when I do these from mongo console or from another client that nodejs mongodb library.

It doesn't matter if .find(query) or .aggregate(pipeline) is used - it fails in both cases.

```
error: error while running query { MongoError: geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }
    at Function.MongoError.create (node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (node_modules/mongodb-core/lib/cursor.js:191:36)
    at Callbacks.emit (node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at .messageHandler (node_modules/mongodb-core/lib/topologies/server.js:282:23)
    at Socket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:273:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
    name: 'MongoError',
            message: 'geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }',
            ok: 0,
            errmsg: 'geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }',
            code: 16604 }
error: search search geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }
```

**Comment by svenvarkel** [comment]
It was my mistake, my connection string was misconfigured and pointed queries towards a wrong database.

**Comment by KunalNischal** [comment]
showing me the same error, i dont know how to resolve it
{"name":"MongoError","message":"geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: \"no geo indices for geoNear\" }","ok":0,"errmsg":"geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: \"no geo indices for geoNear\" }","code":16604}

my schema is -

    var fb_user_schema = mongoose.Schema({
    fb_id: String,
    name: String,	
    picture:String,
    birthday: String,
    email: String,
    location: String, 
	
	photos: 
	[{
		geometry:{
			type: { type: String },
			coordinates: [Number]
		},
		image_link:String,
		description:String,
		location:String,
		latitude:Number,
		city:String,
		state:String,
		longitude:Number,
		country:String,
		album_name:String,
		reason:String,
		category:String
	}]
}


var MongoClient = require('mongodb').MongoClient;

	var URL = 'mongodb://localhost:27017/test';
	MongoClient.connect(URL, function(err, db) {
		if (err) { 
			res.send("error in database!");
		}

	db.collection("fb_user_modal").ensureIndex({"photos":"2dsphere"});
	
    fb_user.aggregate([
        {
       "$geoNear": {
        "near": { 
            "type": "Point", 
            "coordinates": [ 76.99279 , 30.719296 ]
        },
        "distanceField": "dist.calculated",
        "maxDistance": 2,
        "includeLocs": "dist.geometry",
        "num": 5,
        "spherical": true
    }}
    ],function(e, docs){
    	if (docs == undefined || e) {
    		res.json({
    			status: 0, err: e
    		});
    	} else {
    		res.json({
    			status: 1,
    			data: docs
    		});
    	}

    });
})

**Comment by svenvarkel** [comment]
Hi

In your query you need to query the whole geometry object, I guess.

That's how I'm doing it and it works:

`
let longitude = <a coordinate>;
let latitude = <a coordinate>;

let query = {
      geometry: {
        $near: {
          $geometry: {
            type: 'Point',
            coordinates: [longitude, latitude]
          },
          $maxDistance: 1000
        }
      }
    };
`
