### ISSUE TITLE
set socket timeout before write to server

### ISSUE THREAD

**Issue by guillaume-lin** [christkv/mongodb-core#129]
hi, 
   is it possible to set socket timeout before write to mongo server and clear the timeout after receive response from server?
      I am using mongoose, and mongoose rely on this library. when  mongo server exit unexpectedly, the client will wait for a long time to be notified.  I would expect  the client being notified in seconds.

**Comment by christkv** [comment]
no, you should use maxTimeMS to correctly terminate operations
