### ISSUE TITLE
pool destroyed on version 2.2.x

### ISSUE THREAD

**Issue by iamdoron** [christkv/mongodb-core#130]
I upgraded to mongodb driver 2.2.6 (mongodb-core@2.0.8), and I started seeing `MongoError: pool destroyed`. I was able to find a reproducible code on my environment (a mongos deployment with ssl). If I use `poolSize: 1` it is highly reproducible on any version from 2.2.0 to 2.2.6

```
 MongoError: pool destroyed
    at Pool.write (./node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:842:12)
    at WireProtocol.getMore (./node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:236:14)
    at Cursor._getmore (./node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:282:35)
    at nextFunction (./node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:603:12)
    at Cursor.next [as _next] (./node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:681:3)
    at nextObject (./node_modules/mongodb/lib/cursor.js:673:8)
    at Cursor.next (./node_modules/mongodb/lib/cursor.js:262:12)
    at Cursor._read (./node_modules/mongodb/lib/cursor.js:1067:8)
    at Readable.read (_stream_readable.js:355:10)
    at flow (_stream_readable.js:772:26)
    at emitReadable_ (_stream_readable.js:439:3)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) name: 'MongoError', message: 'pool destroyed' 
```

the code to reproduce :

```javascript
const collection = db.collection("tempCollection");
  collection.remove({}, (err) => {
    if (err) return console.trace(err);
    collection.createIndexes([{key: {number: 1}}], (err) => {
      const documents = [];
      for (var i = 0; i < 30000; i++) {
        documents.push({number: i % 15, prop: '+ftnmrzxEcb+0wCcZjC/YWKP5K0M33FC+FyTaPKxCbyEkFWmXgdU+QW7I6HxDmUPjN8='})
      }
      collection.insertMany(documents, (err) => {
        if (err) return console.trace(err);
        console.log("finish inserting documents...");
        const cursor = collection.find({});
        cursor.on('error', (err) => { console.error(err); })
        cursor.on('data', () => {});
      })
    })
  })
```
running with the following options:
```javascript
const mongoOptions = {
 mongos: {
    ssl: true,
    sslValidate: true,
    sslCA: ca,
    poolSize: 1,
    acceptableLatencyMS: 100,
    socketOptions: {
      keepAlive: 120
    }
  }
}
```
Another related issue: When the error is emitted the stream continues to use the write function, and if you connect it to another stream you get `Error: write after end`
meaning: cursor emits 'error'  (pool destroyed) =>  cursor emits 'end' => cursor emits 'data'

**Comment by christkv** [comment]
Seems to work here without an error. Addresses are mongos servers. However I did find something weird when only providing a single seed.

```js
var mongodb = require("./"),
  ObjectID = mongodb.ObjectID,
  CoreConnection = mongodb.CoreConnection,
  CoreServer = mongodb.CoreServer;

var uri = "mongodb://localhost:51000,localhost:51001/test";

// var openThenClose = function(count){
var MongoClient = mongodb.MongoClient;

MongoClient.connect(uri, {}, function(err, db) {
  const collection = db.collection("tempCollection");
  collection.remove({}, (err) => {
    if (err) return console.trace(err);
    collection.createIndexes([{key: {number: 1}}], (err) => {
      const documents = [];
      for (var i = 0; i < 30000; i++) {
        documents.push({number: i % 15, prop: '+ftnmrzxEcb+0wCcZjC/YWKP5K0M33FC+FyTaPKxCbyEkFWmXgdU+QW7I6HxDmUPjN8='})
      }
      collection.insertMany(documents, (err) => {
        if (err) return console.trace(err);
        console.log("finish inserting documents...");
        const cursor = collection.find({});
        cursor.on('error', (err) => { console.error(err); })
        cursor.on('end', () => { console.log('end'); db.close(); })
        cursor.on('data', () => {});
      })
    })
  })
});
```

**Comment by christkv** [comment]
9380a91e0affbd2d1a75221f6c9f5518e6bc79ae

**Comment by iamdoron** [comment]
I was able to reproduce it also in 2.2.7

I tried using [mongodb-topology-manager](https://github.com/christkv/mongodb-topology-manager), and I wasn't able to reproduce it - maybe it's something that surfaces only on a real network of instances that are not on the same computer

**Comment by christkv** [comment]
@iamdoron if you can enable debugging in the driver and post the logs that would be extremely useful. Without being able to reproduce it's hard to figure out what could be happening.  Also describing the topology setup you have would be useful.

**Comment by iamdoron** [comment]
We are using Compose MongoDb deployment - there are 2 mongos 'portals' through which we connect via ssl. They are connected to a replica set, and there are no sharded collections. 
The servers roles (according to compose):
<img width="99" alt="compose topology" src="https://cloud.githubusercontent.com/assets/3956042/17836252/fcba47dc-6793-11e6-938c-f546033f0dfe.png">

The log:
[output.log.zip](https://github.com/christkv/mongodb-core/files/428750/output.log.zip)

**Comment by christkv** [comment]
Hi can you test against the 2.2 branch of the driver as I've added some commits and don't have access to an environment like the one you have for testing purposes

just do

npm i mongodb/node-mongodb-native#2.2 --save

**Comment by iamdoron** [comment]
Thanks

I'm getting the same error using commit 8d061bc6df6131889b633cc0aa4de22ea7f8c699.
npm results:

```
mongodb-core@2.0.9  (git://github.com/christkv/mongodb-core.git#8d061bc6df6131889b633cc0aa4de22ea7f8c699)
```
[output.log 2.zip](https://github.com/christkv/mongodb-core/files/428778/output.log.2.zip)

**Comment by christkv** [comment]
would it be possible to provide me with a test user to just run the script and debug ?

**Comment by brianlukoff** [comment]
I'm seeing the same issue -- also on Compose.
