### ISSUE TITLE
Callback not called on Linux with 2.2.6

### ISSUE THREAD

**Issue by andreialecu** [christkv/mongodb-core#132]
I'm coming from 2.1.18 where this worked without a problem.

So there seems to be a weird situation going on. I have a particular `findAndModify` call that doesn't do anything when running on Heroku/Linux, but it works properly on a Windows dev machine.

I have verified that simply swapping the driver version back to 2.1.18 makes it work again on Heroku/Linux without any other changes. Both 2.1.18 and 2.2.6 work on Windows.

The callback is never called, and neither is the database updated on 2.2.6.

The call looks like this:

```javascript
                                col.findAndModify({
                                    id: id,
                                    lastLogDate: { $lt: parser.lastLogDate }
                                }, [['lastLogDate', 'desc']], {
                                    id: id,
                                    lastLogDate: parser.lastLogDate,
                                    summary: summary
                                }, {
                                    upsert: true,
                                    new: true
                                }, (err, object) => {
```

There is no syntax error of any sort, and no error thrown. The lines immediately following the call all work properly.

Any ideas?

**Comment by andreialecu** [comment]
Perhaps I should've opened this issue in the driver's github page, but I believe it to be related to this package instead.

**Comment by andreialecu** [comment]
There is one thing for me to try, which I just thought about. I'm using newrelic, and I think they monkey patch the driver to add some instrumentation (query duration, etc). Perhaps it interferes with 2.2.6 just on Linux for whatever reason, and not on Windows. I'll have to try disabling newrelic and see if there's any change.

**Comment by andreialecu** [comment]
Is it possible that this is the same issue as the one fixed by https://github.com/christkv/mongodb-core/commit/6933de686a4f7afd5a4a1dcef37cc9f1961b1c44, since I'm also using a single member replica set?

**Comment by christkv** [comment]
very likely, I'm preparing a 2.2.7 release to address the issue

**Comment by andreialecu** [comment]
I can confirm that 2.2.7 fixes this. 👍
