### ISSUE TITLE
No valid replicaset members found when a secondary is not available on the network

### ISSUE THREAD

**Issue by jakesjews** [christkv/mongodb-core#144]
This is with version 2.0.12, mongodb 3.2.10 and ubuntu 14.04.

You will need either 3 VMs or 3 physical servers to replicate this issue. This does not happen if the service is only stopped while the server is on the network or if the script is running before the node leaves the network.
 
Steps to replicate

- Spin up a replica set on three linux servers
- Disconnect the network from one of the secondary servers either by pulling out a network cable or using ifdown on the interface
- Run this script on the remaining secondary node which is still on the network

  ```
  var ReplSet = require('mongodb-core').ReplSet;
  var replSet = new ReplSet([
    { host: server1Ip, port: 27017 },
    { host: server2Ip, port: 27017 },
    { host: server3ip, port: 27017 }
  ]);

  replSet.on('connect', function(_server) {
    setInterval(function() {
      _server.command('system.$cmd', { ping: 1 }, function(err, result) {
        if (err) {
          console.error(err);
        } else {
          console.log(result.result);
        }
      });
    }, 1000);
  });
  ```

- The connect never happens and eventually an error is thrown saying 'no valid replicaset members'

**Comment by christkv** [comment]
Make sure you are using the replicaset names returned from rs.config() as your connection string, they must be resolvable by the driver for reconnect to work.

**Comment by jakesjews** [comment]
Yeah they match.

**Comment by jakesjews** [comment]
The names match. Connections work ok if the mongo service is off but the network is up.

**Comment by christkv** [comment]
if the network is down you are beholden to the socketTimeoutMS parameter and nothing will happen until those trigger timeout events.

**Comment by jakesjews** [comment]
Does it default to 30 seconds? I ran it for a few minutes to make sure it wasn't the timeout threshold. I can make a video when I get in the office.

**Comment by christkv** [comment]
No there should be enough info to try to reproduce it using the mock library I have.

**Comment by christkv** [comment]
2.2.11 will be released tomorrow I suggest retrying with it

**Comment by christkv** [comment]
please reopen if still happening with 2.2.11
