### ISSUE TITLE
Sometimes replica set master reference doesn't change after network loss

### ISSUE THREAD

**Issue by jakesjews** [christkv/mongodb-core#145]
This is with version 2.0.12, mongodb 3.2.10 and ubuntu 14.04.

This issue may be related to #144 and the setup is pretty similar.

You will need either 3 VMs or 3 physical servers to replicate this issue. This does not happen if the service is only stopped while the server is on the network or if the script is running before the node leaves the network.
 
Steps to replicate
- Spin up a replica set on three linux servers
- Start this script on all three nodes

  ```
  var ReplSet = require('mongodb-core').ReplSet;
  var replSet = new ReplSet([
    { host: server1Ip, port: 27017 },
    { host: server2Ip, port: 27017 },
    { host: server3ip, port: 27017 }
  ]);

  replSet.on('connect', function(_server) {
    setInterval(function() {
      _server.command('system.$cmd', { ping: 1 }, function(err, result) {
        if (err) {
          console.error(err);
        } else {
          console.log(result.result);
        }
      });
    }, 1000);
  });
  ```

- Disconnect the network from the master server either by pulling out a network cable or using ifdown on the interface.
- Most of the time (but not always) one of the scripts running on one of the nodes still connected to the network will get stuck in a loop throwing errors trying to connect to the old master.

**Comment by christkv** [comment]
Make sure you are using the replicaset names returned from rs.config() as your connection string, they must be resolvable by the driver for reconnect to work.

**Comment by christkv** [comment]
can you confirm an actual election takes place and a new primary is in fact elected.

**Comment by jakesjews** [comment]
Yeah :( I can make a video if it helps

**Comment by christkv** [comment]
2.2.11 will be released tomorrow I suggest retrying with it

**Comment by christkv** [comment]
please reopen if still happening with 2.2.11

**Comment by jakesjews** [comment]
@christkv with the latest driver most of the time the script will hang forever even after a new master is elected. I have a video at http://recordit.co/GXpTLCCakd if you want to see it happen

**Comment by jakesjews** [comment]
It looks like I don't have permission to reopen the issue should I make a new one?
