### ISSUE TITLE
Unescapable while(true) loop

### ISSUE THREAD

**Issue by d10n** [christkv/mongodb-core#152]
Caused by this commit:
https://github.com/christkv/mongodb-core/commit/2fb9e8273d177e2c8ae450856a81281b45ac2c75#diff-95549f1db7facd9411362e6554f63e2fR1122

If connection.destroyed is true, connection.monitoring is false, and that is the only connection in availableConnections, the while(true) loop never exits and the node process jumps to 100% CPU

**Comment by christkv** [comment]
Fixed
