### ISSUE TITLE
ReplicaSet connection does not close

### ISSUE THREAD

**Issue by tokafew420** [christkv/mongodb-core#156]
Hi,

I'm experiencing an issue where the mongodb connection does not close when querying against a replicaSet. I'm not entirely sure if this is a bug or if I'm missing something else.
Here's an example of my test:
```javascript
var MongoClient = require('mongodb').MongoClient,
    assert = require('assert');
var url = 'mongodb://admin:admin@xxx:27017,xxx:27018,xxx:27019/test?authSource=admin&replicaSet=rs';

MongoClient.connect(url, function (err, db) {
    assert.ifError(err);

    db.collection('test').find({ 'name': 'tom' }, function (err, docs) {
        assert.ifError(err);
        console.log(docs);
        db.close();
    });
});
```
In this example, the callback gets called but node does not exit.

Another interesting note is when using the `count` function, the callback is never called.
For example:
```javascript
    db.collection('test').count({ 'name': 'tom' }, function (err, count) {
        assert.ifError(err);
        console.log(count);
        db.close();
    });
```

However if doing a `find` then `count`, the callback is called (but again node does not exit.)
For Example: 
```javascript
    db.collection('test').find({ 'name': 'tom' }).count(function (err, count) {
        assert.ifError(err);
        console.log(count);
        db.close();
    });
```

This appears to be related to changes made in commit 5711f7a87434fe18b9f18c831864994ac0858ad1
If I revert to **mongodb-core@2.1.2** then it works as expect again.

Environment:
**node:** v5.9.1
**MongoDB:** v3.0
**mongodb package:** v2.2.21
**mongodb-core package:** v2.1.6

**Comment by christkv** [comment]
Moved to https://jira.mongodb.org/browse/NODE-919

**Comment by tokafew420** [comment]
@christkv Thanks for spending your time on this. Please let me know if I can help in any way. I probably can't since I'm still a noob at this, but the offer is still open. 😅

**Comment by christkv** [comment]
I think I've figured out what was wrong and it should be in the next release. It does eventually close with 2.2.21 but it takes 10 seconds.
