### ISSUE TITLE
Encountered exception while executing Javascript. Invalid argument. Query root must be specified.

### ISSUE THREAD

**Issue by adambarghouthi** [christkv/mongodb-core#158]
Hi guys,

I have my parse server which uses Mongodb-Core on Azure now and everything has been working great for a month. Just today when Parse shut down I'm getting this error in my server console:

Error generating response. { [MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}

Don't know what the problem is.
I'm wondering what this could be from, any ideas? 

Thank you!

**Comment by christkv** [comment]
if this is parse related you should open a ticket on tracker as I don't know the parse code and not going to be able to deep dive into what they are doing differently from the parse service.
