### ISSUE TITLE
"current" MongoDB connections increase with each request to an API depending on mongodb-core

### ISSUE THREAD

**Issue by chaddjohnson** [christkv/mongodb-core#160]
Hi guys,

Thank you for the great, free software!

I'm using Mongoose which depends on mongodb (package) which depends on mongodb-core.

I recently upgraded from mongoose 4.0.x to 4.8, and I noticed that the whenever I make a request to my Express-based API, the MongoDB query `db.serverStatus().connections` shows an increase in the "current" connections.

I traced the problem to this package, mongodb-core, version 2.0.13. Mongoose 4.6.5 upgraded mongodb (package) which upgraded mongodb-core to 2.0.13. If I manually install mongodb-core 2.0.12 in place of 2.0.13, the problem I described goes away (i.e. when I make requests to my API, the "current" connections remains constant).

Is this possibly a bug? Or is there a known cause for this? Perhaps it's related to the following change noted in the history for 2.0.13?

> Refactoring to support pipelining ala 1.4.x branch will retaining the benefits of the growing/shrinking pool

Thank you!

**Comment by christkv** [comment]
The number of connections will vary between 1 and maxPoolSize as load is increases or decreases. The driver grows the pool up to maxPoolSize if there are more operations in the queue than available connections.

**Comment by mqaiserm** [comment]
I have the same issue. I have server: {poolSize: 25} setting in db connection option. After upgrading to mongoose 4.8, its not utilizing connections from the pool. On every request, its keep opening new connections.

Before upgrading to 4.8.0, we were using 4.0.x and we did not have this problem. On every request, it was using connection from the pool.

**Comment by christkv** [comment]
can you put together an example that replicates the behavior you are seeing (maybe a simple repo)

**Comment by christkv** [comment]
closing as no response

**Comment by mbroadst** [comment]
@biharibipin this is the github project for the node.js driver, if you have found a bug in the node.js or Java drivers please file a ticket on their respective JIRAs.
