### ISSUE TITLE
Security Misconfiguration issues

### ISSUE THREAD

**Issue by samdai** [christkv/mongodb-core#166]
Currently I used this node module in my project, when I used checkmarx tool to scan the source code, found a Security Misconfiguration security issue, for example this line https://github.com/christkv/mongodb-core/blob/2.0/lib/auth/gssapi.js#L90, is there any solution to fix it? thanks.

**Comment by christkv** [comment]
Sorry but without knowing the tool and it's output it might every well be a false positive. Frankly I don't know any good tool that works properly for dynamic languages due to the inherent problems of not having types.

**Comment by samdai** [comment]
thanks your quick response
