### ISSUE TITLE
TypeError: Cannot read property 'wireProtocolHandler' of null

### ISSUE THREAD

**Issue by jlutzhbo** [christkv/mongodb-core#168]
Getting an error that occurs sporadically and have not been able to reproduce locally yet, but here is the crux of the issue.

The error is being thrown "TypeError: Cannot read property 'wireProtocolHandler' of null".

The error occurs in the core cursor next call, specifically here: https://github.com/christkv/mongodb-core/blob/2.0/lib/cursor.js#L568. Thus, at some point, `self.server` is being set to null, presumably here, since this is the only place where this is set, other than initialization: https://github.com/christkv/mongodb-core/blob/2.0/lib/cursor.js#L546

So my assumption is that this method is returning null at some point. https://github.com/christkv/mongodb-core/blob/2.0/lib/topologies/replset_state.js#L607

Aside: There is a spot in this method where null is explicitly returned, though this is not my specific error, as this is for a different read preference: https://github.com/christkv/mongodb-core/blob/2.0/lib/topologies/replset_state.js#L681. However, this illustrates the need for more error checking / logging around this issue. If this method cannot pick a server, we should probably log a warning, at the very least. Also, we should probably check for a null value here: https://github.com/christkv/mongodb-core/blob/2.0/lib/cursor.js#L546).

Here are the relevant connection options that I am using:

```
{
    "autoReconnect": true,
    "connectTimeoutMS": 10000,
    "connectWithNoPrimary": true,
    "poolSize": 100
}
```

and connection URI options:

```
{
    "readPreference": "nearest",
    "readPreferenceTags": "dc:west",
    "replicaSet": "rs0",
    "wtimeoutMS": 5000
}
```

We are using a replica set with three nodes in a west data-center and three nodes in an east data center. (Our servers in the west are configured to connect to the west nodes via those readPreferenceTags).

**Comment by christkv** [comment]
Turn off connectWithNoPrimary and it will work, there is a fix for this in the next upcoming bug fix release 2.2.25 that will be out at the end of the month. You should not be using connectWithNoPrimary unless you specifically are targeting using only secondary reads.

**Comment by jlutzhbo** [comment]
@christkv Thank you for the quick response. We are using `connectWithNoPrimary` because we have a bifurcated cluster -- with the primary in one region -- which replicates across the country using a somewhat unreliable VPN. We need to be able to connect from the application service in the region without the primary even if the VPN goes down. So I think I'll wait for the fix. Is there a JIRA ticket I can reference? Thanks!

**Comment by christkv** [comment]
This is the actual commit fix https://github.com/christkv/mongodb-core/commit/720251fa966b11902ea3fe369d8296cbf39d403a
