### ISSUE TITLE
MongoError: Invalid collection name: test.$cmd

### ISSUE THREAD

**Issue by e2tox** [christkv/mongodb-core#172]
I got the error when trying to run mongodb command using namespace of `COLLECTION + '.$cmd'`

2.1.8 is working but 2.1.9 throw an exception

```
const connection = new Server({}});
connection.command('test.$cmd', ... )
```

**Comment by christkv** [comment]
can you provide a failing test case ?

**Comment by e2tox** [comment]
1. create one db `develop` and collection `user`
2. run following script.
3. got error `MongoError: Invalid collection name: develop.$cmd`
4. node: v6.10.0,  mongodb-core: 2.1.9, mongodb: 3.4.0

```javascript
var Server = require('mongodb-core').Server

// Set up server connection
var server = new Server({
  host: 'localhost'
  , port: 27017
  , reconnect: true
  , reconnectInterval: 50
});

// Add event listeners
server.on('connect', function (_server) {
  console.log('connected');
  
  var db = 'develop';
  
  const cmd = {
    "find": "user",
    "filter": {
      "$or": [
        { "provider": "google", "providerData.id": "placeholder" },
        { "additionalProvidersData.google.id": "placeholder" },
        { "email": "placeholder" }
      ]
    },
    "limit": 1,
    "projection": {},
    "sort": {}
  };
  
  server.command(`${db}.$cmd`, cmd, {}, (err, response) => {
    console.log(err, response);
  });
  
});

server.on('close', function () {
  console.log('closed');
});

server.on('reconnect', function () {
  console.log('reconnect');
});

// Start connection
server.connect();

```

**Comment by e2tox** [comment]
above script will fail only 2.1.9
will get result `{ cursor: { firstBatch: [], id: 0, ns: 'develop.user' }, ok: 1 }` with 2.1.8

**Comment by e2tox** [comment]
Thank you so much. I really appreciate your great work and the fantastic library.

**Comment by christkv** [comment]
Why are you executing the find command and not using the cursor method ?

**Comment by e2tox** [comment]
It's return 1 record at most in this case. In other case. i will use count/find and cursor method to pipe the results to a stream and transfer using protobuf.
