### ISSUE TITLE
connection pool writes to destroyed connections

### ISSUE THREAD

**Issue by jmholzinger** [christkv/mongodb-core#179]
I've been encountering a strange issue when the MongoDB server abruptly shuts down. Most of the time the connection recovers when the MongoDB server comes back online, but if the client was writing to the connection when the server goes down a "write after end" error is thrown. This seems to be expected, but I cannot seem to capture this error and handle it, the error doesn't appear to be passed to the MongoDB driver's connection object.

Here's the stack trace:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at Socket.Writable.write (_stream_writable.js:244:5)
    at Socket.write (net.js:661:40)
    at Connection.write (C:\Users\jholzinger\WebstormProjects\dtp-services\node_modules\mongodb-core\lib\connection\connection.js:516:53)
    at C:\Users\jholzinger\WebstormProjects\dtp-services\node_modules\mongodb-core\lib\connection\pool.js:1242:26
    at waitForAuth (C:\Users\jholzinger\WebstormProjects\dtp-services\node_modules\mongodb-core\lib\connection\pool.js:1100:39)
    at C:\Users\jholzinger\WebstormProjects\dtp-services\node_modules\mongodb-core\lib\connection\pool.js:1108:5
    at C:\Users\jholzinger\WebstormProjects\dtp-services\node_modules\mongodb-core\lib\connection\pool.js:972:21
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I'm not using the MongoDB driver directly, I'm using Mongoose (4.8.6) for most of my DB interactions. But event if I attach an error handler to the native driver's connection I'm not able to capture the error.

```
var connection = mongoose.createConnection(...);
...
connection.db.on('error', function(err) {
    console.log('this is never called, but the program crashes due to an unhandledException');
});
```

Using the stack trace, I manually added a check for a destroyed connection before writing to the connection. It seems to fix my problem, but I'm not sure if this is "correct", the data to be written will be lost at this point. I'm not familiar enough with this code base to propose a "correct" solution, for all I know the mistake could be on my end.

Here's the code that I changed...
lib/core/connection/connection.js
```
Connection.prototype.write = function(buffer) {
  var i;
  // Debug Log
  if(this.logger.isDebug()) {
    if(!Array.isArray(buffer)) {
      this.logger.debug(f('writing buffer [%s] to %s:%s', buffer.toString('hex'), this.host, this.port));
    } else {
      for(i = 0; i < buffer.length; i++)
        this.logger.debug(f('writing buffer [%s] to %s:%s', buffer[i].toString('hex'), this.host, this.port));
    }
  }

  if (!this.connection.destroyed) { // Don't write to the connection if it's destroyed...
    // Write out the command
    if(!Array.isArray(buffer)) return this.connection.write(buffer, 'binary');
    // Iterate over all buffers and write them in order to the socket
    for(i = 0; i < buffer.length; i++) this.connection.write(buffer[i], 'binary');
  }
}
```

The reason I've opened this issue is because I'm attempting to recover from situations like this without the application crashing, and without resorting to using 'uncaughtException' events to hack my way around the problem. Any feedback would be helpful. Thanks.

**Comment by christkv** [comment]
I would upgrade mongoose to ensure you are on 2.2.26 first as there are some fixes that will impact the behavior you are seeing.

Also unfortunately I think the fix you did might not work as it might lead to the operations callback never being called.

**Comment by christkv** [comment]
I've added some more paranoia checks to the code.

**Comment by jmholzinger** [comment]
At this point I'm not certain mongoose is the culprit, I'm also sharing the database connection in a mosca mqtt server, so it may be related to how the mosca server uses mongodb as a backend/persistence mechanism. I will take a deeper dive and see what I can find, the stack trace is pretty limited in terms of information, so it's not really clear where the error originates from.

**Comment by jmholzinger** [comment]
I was able to determine with some confidence that mosca was not handling this scenario the way I would expect, switching to aedes resolved my issues supporting this use-case.
