### ISSUE TITLE
Where is pool in Mongodb-core?

### ISSUE THREAD

**Issue by robbie-mac** [christkv/mongodb-core#182]
So if you look at the [documentation](http://mongodb.github.io/node-mongodb-native/core/driver/reference/pool/) there is a reference to the connection pool. If you look at the [API Reference](http://mongodb.github.io/node-mongodb-native/core/api/index.html) no mention of pool. So I poked around and I can find pools [source](https://github.com/christkv/mongodb-core/blob/2.0/lib/connection/pool.js) BUT, I cant find any reference to this file anywhere else in the source.

Wondering if pool is intended for the full driver, or if it is really supposed to be used in the core driver but got missed.

Or am I missing something else entirely.

**Comment by christkv** [comment]
You are missing something completely :) it's wrapped by the Server object in server.js and is an internal class not exposed to end users.

**Comment by robbie-mac** [comment]
Ah, thanks. I was planning on playing around with pool.write and others that were shown in the docs, but if its an internal object, Ill leave well enough alone.

Thanks.
