### ISSUE TITLE
db.command({ ping: 1 }) gives  SSL UNABLE_TO_VERIFY_LEAF_SIGNATURE on self signed SSL connection

### ISSUE THREAD

**Issue by ebdrup** [christkv/mongodb-core#19]
I have a ping command on a replset using ssl=true in the connectionstring. With self signed certificates.
It seems the latest release causes SSL UNABLE_TO_VERIFY_LEAF_SIGNATURE on db pings.

Is there any way to ping without the need for strict SSL certificate checking?

I haven't had time to debug extensively...

**Comment by christkv** [comment]
just using mongodb core or the 2.0 driver ?

**Comment by ebdrup** [comment]
My bad, might be because `replicaSet=XXX` is missing in the connectionstring. Investigating.

using mongodb-native. So it's not the latest release that's an issue since version is locked..

**Comment by ebdrup** [comment]
Closing this. Just needed to add:
```js
sslValidate: false
``` 
in dbOptions... Internal communication issue, sorry for bothering you.
