### ISSUE TITLE
[Question] Pool reconnection explain

### ISSUE THREAD

**Issue by vaseker** [christkv/mongodb-core#25]
Hello!
I have a question about pool reconnection:

I've a heavy query to mongodb replicaset and defined (specially low) socketTimeoutMS. 
When query execution time reachs socketTimeoutMS, driver closes this pool instance. This is ok. But I cannot see reconnection executions. 

If call query again, mongo-core debug says nothing at all.

Even in this state mongo driver doesn't respond to connection lose. Just hangs.

There is connection options to MongoClient
```js
var socketOptions = {
    connectTimeoutMS: 10000,
    socketTimeoutMS : 60000
};
var mongoOptions = {
    db: {
        readPreference: 'secondaryPreferred',
        native_parser: true
    },
    server: {
        socketOptions: socketOptions
    },
    replSet: {
        haInterval: 200,
        secondaryAcceptableLatencyMS: 15,
        socketOptions: socketOptions
    }
};
```

With this options I'm expecting default `auto_reconnect: true`. What am i doing wrong?

Thank you.

[I've shared trimmed debug log of this](https://yadi.sk/i/a3x5IcBogtvkZ)

PS. Sorry for my English

**Comment by vaseker** [comment]
Is this question related with https://github.com/christkv/mongodb-core/blob/master/TODO?

**Comment by christkv** [comment]
whatever was in you [STACKTRACE] probably caused an exception that killed the driver instance. have you considered a long sockettimeout and using maxTimeMS to set an upper boundary on your query instead, avoiding socket connection closures

**Comment by vaseker** [comment]
Oh. My bad. Thank you!
