### ISSUE TITLE
Option to allow invalid hostnames in TLS validation

### ISSUE THREAD

**Issue by robinvenneman** [christkv/mongodb-core#29]
It would be useful in some cases to allow TLS validation while excluding hostname validation, more specifically by allowing invalid hostnames from the client, similar to these issues:
- https://jira.mongodb.org/browse/PYTHON-834
- https://support.symantec.com/en_US/article.TECH141351.html

MongoDB already has an "allowInvalidHostnames" configuration option. However, for this to work in mongodb-core's connection options it might require updates to Node's TLS.connect() method.

**Comment by christkv** [comment]
you can try

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

I'm probably not going to hack into the ssl process to work around this.

**Comment by jgraham909** [comment]
Would you be open to a PR to pass forward checkServerIdentity? As documented in https://nodejs.org/api/tls.html#tls_tls_connect_options_callback 

Node.js's hostname checking is too strict and fails in the case of wildcard certificates.

NODE_TLS_REJECT_UNAUTHORIZED turns off *all* certificate validation.

**Comment by christkv** [comment]
If you can make it work for 0.10, 0.12 and up. Also I would need some sort of test and test certificate to ensure it works correctly.

**Comment by robinvenneman** [comment]
I've got this code working and added it in node-mongodb-native driver as well, waiting for approval of my employer to open a pull request... Would still need to add a unit test though.

**Comment by jgraham909** [comment]
From reviewing the node.js source it looks like the checkServerIdentity override https://github.com/nodejs/node/commit/bf5e2f246eff55dfc33318f0ffb4572a56f7645a was committed in 0.11.14.

```
node$ git branch -r --contains bf5e2f246eff55dfc33318f0ffb4572a56f7645a
  origin/HEAD -> origin/master
  origin/archived-io.js-v0.10
  origin/archived-io.js-v0.12
  origin/broken
  origin/master
  origin/v0.11.14-release
  origin/v0.11.15-release
  origin/v0.11.16-release
  origin/v0.12
  origin/v0.12.0-release
  origin/v0.12.1-release
  origin/v0.12.2-release
  origin/v0.12.3-release
  origin/v0.12.4-release
  origin/v0.12.5-release
  origin/v0.12.6-release
  origin/v0.12.7-release
  origin/v0.12.8-proposal
  origin/v1.8.0-commit
  origin/v1.x
  origin/v2.0.2
  origin/v2.3.1-release
  origin/v3.3.2-proposal
  origin/v3.x
  origin/v4.0.0-rc
  origin/v4.2.2-proposal
  origin/v4.x
  origin/v4.x-staging
  origin/v5.x
  origin/vee-eight-4.7
````

As such we can make this work for [io.js v1.0.0](https://github.com/nodejs/node/blob/v1.0.0/CHANGELOG.md) and 0.12+ otherwise.

**Comment by christkv** [comment]
in 2.0.53 and 2.1.2
