### ISSUE TITLE
Under certain circumstances undefined values are recorded in database as null values

### ISSUE THREAD

**Issue by jlchereau** [christkv/mongodb-core#31]
See https://github.com/Automattic/mongoose/issues/3169

**Comment by christkv** [comment]
The node driver has never supported the undefined bson type as it was deprecated before I even started writing this driver. undefined is treated as null. To ensure correct behavior you need to delete the property from the object before saving it.

**Comment by jlchereau** [comment]
Delete is 150 times slower than assigning undefined. On a server, it makes a difference.

See: http://webcache.googleusercontent.com/search?q=cache:k-251eM9RkAJ:https://jsperf.com/delete-vs-undefined-vs-null/26+&cd=1&hl=en&ct=clnk&gl=uk

Besides, if you look at the examples provided, this is not always consistent: sometimes it is treated as null, sometimes it is ignored.

**Comment by christkv** [comment]
the problem is that I'm not going to store undefined as it's a deprecated bson type and might well disappear tomorrow . the best I can do is not to serialize it going forward but even that will have to be a new switch as it would break implicit behavior of over 5 years.

**Comment by jlchereau** [comment]
As commented on https://github.com/Automattic/mongoose/issues/3169, I think the best and most consistent behaviour is to ignore undefined as you are suggesting. Storing undefined makes no sense to me.

Note that in mongoose, undefined is ignored most of the time expect in very specific scenarios reported on the above issue.

**Comment by christkv** [comment]
can you open a ticket on the NODE jira project https://jira.mongodb.org/browse/NODE

Just put, please ignore undefined for bson serialization, and reference this ticket. I'm on mobile so a bit hard to do it right now

**Comment by jlchereau** [comment]
See https://jira.mongodb.org/browse/NODE-517

**Comment by christkv** [comment]
should be in the next release hopefully later today.
