### ISSUE TITLE
Unique index not throwing duplicate key error 

### ISSUE THREAD

**Issue by dr-dr** [christkv/mongodb-core#41]
few places where this is used:
 if(result.documents[0]['$err']...) { return callback(MongoError.create(result.documents[0]));
e.g. Server.prototype.command, executeSingleOperation ..

Possible fix:
/lib/connection/commands.js

Response.prototype.parse
...
// tell callers of the response body parsing that an error has occurred due to a unique index error (as one possible scenario) - if there is an error let the document be an error for the top level checking to work..
 if (this.documents[i].writeErrors){
      this.documents[i] = this.documents[i].writeErrors[0];
    }

**Comment by christkv** [comment]
Write errors can be 1:n so they are not returned as a MongoError. I do plan to change it to be returning a MongoBulkError going forward that will provide the results needed. See

https://jira.mongodb.org/browse/NODE-526
