### ISSUE TITLE
Weird GridStore issue going from 1.2.8 to 1.2.9

### ISSUE THREAD

**Issue by amit777** [christkv/mongodb-core#42]
I looked through the code changes, but I didn't see anything that would change the way a GridStore is accessed.  In my test suites, I get an error when trying to create a gfs stream using this code:

apologies for teh vagueness in my report.  But I figured I'd post this in case it's obvious to you all what changed to make this piece of code no longer create a proper stream:

```

var GridStore = mongoose.mongo.GridStore;
var conn;
var connect = function(){
   console.log(`connecting to gridfs:${config.get('gridfs.db')}`);
   conn = mongoose.createConnection(config.get('gridfs.db'), config.get('gridfs.dbOptions'));
};
connect();
conn.on('error', console.log);
conn.on('disconnected', connect);

...

var getStream = function(){
    var db = conn.db;
    var gfs = new GridStore(db, `/opt/sendergen/data/${that.hash}`, "r", {root: 'fs'} );
    return gfs.stream();
};


```

**Comment by christkv** [comment]
you should reopen this in the mongoose project.

**Comment by amit777** [comment]
Hi, sorry to re-open, but I think there may be a bigger issue with the upgrade from 1.2.8 to 1.2.9.  When I revert to 1.2.8, my gridstore issue with my test above is resolved.  However, I noticed another issue with 1.2.9.  I think it has something to do with my standard replicaset setup.  My process crashes every 5 seconds or so.  If I downgrade to 1.2.8, everything seems fine.  Here is the stack trace:

```
TypeError: self.isDead is not a function
    at nextObject (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:576:44)
    at Cursor.next (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:223:12)
    at Store.execute (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/lib/topology_base.js:83:18)
    at null._onTimeout (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:888:31)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by christkv** [comment]
can you provide a free standing code snippet that reproduces the issue as I'm not having much luck getting this to happen.
