### ISSUE TITLE
1.2.8 to 1.2.9 issue

### ISSUE THREAD

**Issue by amit777** [christkv/mongodb-core#43]
Hi, sorry to re-open, but I think there may be a bigger issue with the upgrade from 1.2.8 to 1.2.9. When I revert to 1.2.8, my gridstore issue with my test is resolved in this ticket (https://github.com/christkv/mongodb-core/issues/42) . However, I noticed another issue with 1.2.9. I think it has something to do with my standard replicaSet setup. My process crashes every 10 seconds or so with the following stack trace. However, if I downgrade to 1.2.8, everything seems fine.

```
TypeError: self.isDead is not a function
    at nextObject (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:576:44)
    at Cursor.next (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:223:12)
    at Store.execute (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/lib/topology_base.js:83:18)
    at null._onTimeout (/opt/sgapp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:888:31)
    at Timer.listOnTimeout (timers.js:89:15)

```

Looking at the code changed in 1.2.9, it seems like some replicaset stuff is changed..  I very well could just be coding stuff incorrectly, but this had been working fine for many months until 1.2.9.

**Comment by amit777** [comment]
ugh.. i'm sorry, late night.. trying to figure this out, and this may be a red herring.  i'll repost a ticket if I can get a clearer pictures of what is actually causing my issues..

**Comment by amit777** [comment]
I'm taking a fresh look at this today and will try to get you a minimal example to reproduce.  It's not clear to me why isMasterDiscovery() in mongodb-core/lib/topologies/server.js was removed in 1.2.9.  This seems to be the culprit.   Is it possibly an over site?

**Comment by christkv** [comment]
it was removed due to it causing this problem

https://jira.mongodb.org/browse/NODE-518

**Comment by amit777** [comment]
so I haven't been able to exactly isolate this down.. However, I was able to "fix" the issue with this small patch that checks to see if isDead is defined:

https://github.com/amit777/node-mongodb-native/commit/6a1bacc0c9eef03a790283e30d755b14bf12bd21

I have a feeling there is some sort of race condition that exposes this bug.  Another interesting observation is that I get this stacktrace where my process crashes about 3 times, and then my process seems to run fine.  The process is managed by pm2 and is auto-restarted.  My replica set is 3 nodes.  2 of the nodes including the master are in a different datacenter than where my test machine is.

**Comment by amit777** [comment]
solved.. closing
