### ISSUE TITLE
MongoDB 3.0 support

### ISSUE THREAD

**Issue by RangerMauve** [christkv/mongodb-core#47]
I'm using a library, [promised-mongo](https://github.com/gordonmleigh/promised-mongo) which depends on this module. My cloud provider recently upgraded our DB to be Mongo 3.0 and it seems that every time the server tries to connect to the DB, an `auth failed` error is thrown.
 Does this module support MongoDB 3.0, and is it just the library I'm using that's doing something fishy? Or might it be that it isn't currently supported?

**Comment by christkv** [comment]
you can switch to the latest 2.0.x driver that also has promises and that will do the right thing for 3.0 which is to use the SCRAM-SHA1 auth mechanism which is the default one  in 3.0

**Comment by RangerMauve** [comment]
Is that the [mongodb-native](https://github.com/mongodb/node-mongodb-native) driver that you're referring to? Are there docs that I can reference for how they're supporting promises? Or is it just the pattern where if I omit a callback I'll get a promise out?

**Comment by RangerMauve** [comment]
Awesome, found that it's in the [docs](http://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html) I missed it since it wasn't in the README. I'll go see about how quickly I can migrate this stuff. Thanks for the help!
