### ISSUE TITLE
Server-generated _id of inserted document

### ISSUE THREAD

**Issue by parshap** [christkv/mongodb-core#51]
How do I get the server-generated `_id` of an inserted document that did not have a `_id` property? It is not set on the document object and does not appear to be available in the result object. Here is what I am doing:

```js
var mongodb = require("mongodb-core");
var server = new mongodb.Server();
var doc = { foo: 1 };
server.insert("test.test", [doc], function(err) {
  // _id not available in result
  // doc._id not set
});
```

**Comment by christkv** [comment]
You cannot as the insert does not return the _id, This is the reason the driver generates it's own _id's. What are you planning to use mongodb-core for ? If you plan to use it for your application that's advised.

**Comment by parshap** [comment]
I see now that the mongodb wire protocol does not send back the `_id` at all. I will generate my own `_id` client-side. Thanks.
