### ISSUE TITLE
Stepdowns during a secondary-only query cause the stream to hang indefinitely

### ISSUE THREAD

**Issue by Sebmaster** [christkv/mongodb-core#55]
Repro
1. Spin up a replica set with 2 members + 1 arbiter
2. Fill the `coll` collection (has 500k records on my machine which works fine without having to be quick)
3. Run the script
4. Post stepdown action (I'm using mongo-orchestration, but should be the same with mongo-shell) while it's still running

```js
const mongodb = require('mongodb');
const connString = "mongodb://localhost:1025,localhost:1026,localhost:1027/?readPreference=secondary";
mongodb.Logger.setLevel('info')

function getStream(db) {
  return db.collection('coll').find({}).batchSize(2).stream();
}

mongodb.MongoClient.connect(connString, { replSet: { replicaSet: "55222f68-936f-4a83-b68a-9f0cfa60a2e7" } })
  .then((db) => {

    const stream = getStream(db);
    stream.on('data', (doc) => {
      console.log(Date.now());
    })
    stream.on('error', (chunk) => {
      console.error('Got an error from cursor');
    })
    stream.on('end', () => {
      console.log('Got everything')
    })
  })
  .then(null, console.error);
```
(batchSize is just to show the effect with a small-ish collection)

System is node 4.2.2, mongo 2.6.10, mongodb@2.0.48, mongodb-core@1.2.21.

It's not guaranteed to happen every time, but I can reproduce about every 1-3 stepdown tries. It seems like mongodb-core goes into a monitoring-process loop. It won't throw an error on the cursor so one can retry manually, but won't manage to retry itself either.

I have no idea where that bug could be, I'm trying to find it, but no idea where to even start. Any pointers or ideas what could be wrong? Could of course also be a mongo-native bug, but replicaset reconnection logic seemed to belong here.

**Comment by christkv** [comment]
Hmm this might take some time to reproduce. After you step down, do you see a valid primary being elected at some point ?. Is this a regression you are seeing or something you just caught ?

**Comment by Sebmaster** [comment]
> After you step down, do you see a valid primary being elected at some point ?

Yes. When I do some stepdowns quickly after each other to repro primary election takes a bit longer at times, but they do eventually have an election and a new primary (the cursor doesn't continue though).

 > Is this a regression you are seeing or something you just caught ?

Just caught this, using mongodb-core for the first time.

**Comment by christkv** [comment]
are there complete elections between the step downs ? As in 

1. step down primary
2. wait for primary to be elected
3. step down again

rinse and repeat ?

**Comment by Sebmaster** [comment]
Yeah, mongo-orchestration will fail the stepdown action if the specified server isn't a primary, so that should be the case.

**Comment by christkv** [comment]
I have been able to reproduce it. I will try reproduce it using my mocking library tomorrow. Right now it seems like the monitoring process never detects the new primary and just goes into an infinite loop always querying the secondary. It's as if the primary step down is not properly detected.

**Comment by Sebmaster** [comment]
Woah, cool. For some reason it's now erroring the cursor properly for me. I'm not quite sure I'm actually reproducing the bug we're hitting in production right now, but it's a start in any case :+1:

**Comment by christkv** [comment]
I think it's a timing issue but having the ability make a "fake" server setup and emulation has speed up tracking these down. You can see an example below of how it works.

https://github.com/christkv/mongodb-core/blob/master/test/tests/functional/rs_mocks/failover_tests.js

**Comment by christkv** [comment]
do you have time to check if the master branch of mongodb-core fixes your issues. I can no longer replicate the issue here.

**Comment by Sebmaster** [comment]
Funnily enough, I think that we never had this issue in our tests, since we never had actual stepdowns - the log messages for ismaster updates just incidentally occured the same time a different bug occured. So my testcase just tested stuff which we actually never encountered. Yay coincidences :tada: 

I'll try to replicate with my original testcase either this weekend or Monday though.

**Comment by Sebmaster** [comment]
Oh, it also seems like you forgot to commit the actual step_down test file yet, just as a side note.

**Comment by christkv** [comment]
good point

**Comment by christkv** [comment]
all pushed.

**Comment by christkv** [comment]
any news on the fix

**Comment by Sebmaster** [comment]
Seems like I'm always getting an error on the cursor now, which allows me to reinitialize it, so seems like we're good :tada: Sorry for the delay.

**Comment by christkv** [comment]
awesome good to know :+1: you guys were some of my very first users so there is a bit of sentimental value attached to it :)
