### ISSUE TITLE
Connection pooling doesn't seem to take availability into consideration

### ISSUE THREAD

**Issue by jishi** [christkv/mongodb-core#60]
I have been trying to wrap my head around the implementation of the pooling in this driver, since we seem to suffer from concurrency issues in our application.

The scenario is this: 

A web application with a single instance of mongodb connected and used throughout the app.

One request initiates a long running aggregate query.
Random subsequent requests seems to hang, until the aggregation query finishes.

Looking at the source code, I notice the "checkoutConnection" method in the pool implementation, that seems to grab a connection round-robin style regardless of the state of the connection. Wouldn't this be a problem if that connection is busy with a query? 

I also looked into mongos, which according to the FAQ should consider "busy" connections. Is that the workaround, to rely on mongos for these kind of scenarios? I'm kind of surprised that I can't find anyone else finding this to be a problem, which makes me believe that we are doing something terribly wrong. 

This happens with different poolSizes, but it is more error prone with a small pool size.

**Comment by jishi** [comment]
I wrote a simple test snippet for it:
```
'use strict';

const mongo = require('mongodb');
const poolSize = 5;

let db = mongo.connect('mongodb://localhost/local?maxPoolSize=' + poolSize, (err, db) => {

  let i = 0;
  let collection = db.collection('me');

  let interval = setInterval(() => {

    let query = {};

    if (i%(poolSize*4) == 0) {
      query = {$where: 'sleep(8000)'};
    }

    collection.find(query).toArray()
      .then(((index, q) => {
        return () => console.log('done with query', index);
      })(i++, query))
      .catch((e) => {
        console.error(e)
      });

    if (i == 100) {
      clearInterval(interval);
      db.close();
    }

  }, 1000);

});
```

Which makes it evident that query 5 will wait for query 0 because the round robin will allot it that connection in the pool, even though 4 other connections are idle and available.

**Comment by christkv** [comment]
The pool is used round-robin as you expect. You're hit by the slow train problem. There is no concept of checking in and out connections from the pool so no way for the driver to tell what op takes longer to execute. One strategy used for this is.

Create a seperate pool for the long running aggregation queries only so they do not affect the running

Long term the server will move to multiplexing connections on the sockets which will make this particular problem go away when pipelining ops like what the node driver does.

**Comment by jishi** [comment]
Thanks for responding so quickly. Will multiplexing connections really solve this issue? Do other drivers suffer from the same thing? Connection pooling is handled very differently in most drivers for other DBs, with min/max sizes and scaling to prevent having idle connections on an idle server, what does mongodb do differently that makes this harder to implement?

Would you accept a pull request if we would manage to improve the pooling to serve first idle instead of round-robin them?

**Comment by christkv** [comment]
Multiplexing connections on the server will fix this as multiple threads will be able to service each socket. As of now a single mongod socket is associated with a single thread.

I've already tried the suggestion you are proposing and it did not fix it as you eventually hit the same problem once all connections where no longer idle in a busy application.

I also tried putting in process.nextTick and setTimeout to have operations sit and spin waiting for a socket to appear but this causes excessive cpu usage and affects throughput badly.

My suggestion is still to put the slow ops in it's own dedicated pool. If you this would cause a major refactoring I would suggest it might be the "one" time you can use the global object to pass a connection pool around.

**Comment by christkv** [comment]
feel free to experiment if you wish I'm closing this issue for now.
