### ISSUE TITLE
connectTimeoutMS default

### ISSUE THREAD

**Issue by chrisckchang** [christkv/mongodb-core#61]
The default connectTimeoutMS value, as documented in the [ReplSet](http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html) docs, is 0.

I found the following line that suggests the default value is 10000 ms: https://github.com/christkv/mongodb-core/blob/master/lib/topologies/replset.js#L177

Which value is the correct default? Thanks!

**Comment by christkv** [comment]
10000 ms is the correct value, updated docs.
