### ISSUE TITLE
3.2 compatability

### ISSUE THREAD

**Issue by paton** [christkv/mongodb-core#62]
We're getting "MongoError: topology was destroyed" when upgrading from MongoDB 3.07 to 3.2 using the mongoose ORM.

The 3.2 release notes says "A driver upgrade is necessary to support find and getMore." -- I suspect this is the cause?

**Comment by christkv** [comment]
I think you code is calling close somewhere and then trying to reuse the connection. Most likely you are upgrading from a Mongoose version using the 1.4.x branch to the 2.0.x driver branch where this is illegal. This was needed to avoid the issue of dangling connections that could happen in some weird corner cases when monitoring replicasets.

**Comment by paton** [comment]
We're using mongoose `4.2.9` which uses mongodb-core `2.0.49`.

No changes in versions of those dependencies -- all we did was a database upgrade from 3.0.7 to 3.2.0

**Comment by christkv** [comment]
if you can make a minimum reproduction example I'll be happy to take a look at it tomorrow to make sure there is no obvious problem here.
