### ISSUE TITLE
Potential bug in lib/connection/pool.js

### ISSUE THREAD

**Issue by mkw** [christkv/mongodb-core#66]
I have a semi-consistent case of getting a "sockets closed" error on a batch process when using version 1.2.26 of mongodb-core with Node 0.12.7 via Mongoose.  It ONLY wails when connected via a replica set with multiple members (test environment is 2 instances and a tie breaker hosted by MongoLab on AWS) and the exception is:
```
15:11:39.947 - error: [13592] Error listing Question: MongoError: server ds045980-a1.mongolab.com:45980 sockets closed
    at null.<anonymous> (/Users/mkw/dev/tr/trustradius/node_modules/mongodb-core/lib/topologies/server.js:331:47)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/Users/mkw/dev/tr/trustradius/node_modules/mongodb-core/lib/connection/pool.js:101:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/mkw/dev/tr/trustradius/node_modules/mongodb-core/lib/connection/connection.js:142:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:485:12)
```
Note that the stacktrace above is on OS X, but the same error occurs on Linux hosted by Heroku.

After studying the error, I'm posting it here, as well as in Automattic/mongoose/issues/3588, because it appears to me to expose a bug in lib/connection/pool.js.

To determine this, I added a bunch of debug messages via breakpoints and am now I'm attaching a zip file two logs named success.log and failure.log from runs that were successful and not, respectively:
- The "Connection" prefix log messages are from event handlers in mongo-core/lib/connection/connection.js
- The artificial stack trace error is generated by a breakpoint log message from Connection.prototype.destroy() in mongo-core/lib/connection/connection.js.
- The "Pool" prefix log messages are from event handlers in mongo-core/lib/connection/pool.js.
- The "NativeConnection" prefix log messages are from event handlers in mongoose/lib/drivers/node-mongodb-native/connection.js

Additionally, I used the "longjohn" module to get stack traces including the source of the callback for the final failure.

What is particularly strange to me is that, if I'm reading it right, when a single connection gets a socket close, all of the connections in the pool appear to have destroy() via pool.js#closeHandler() calling self.destroy().  Shouldn't a connection pool just be destroying the connection with the error and replacing it?  I might be misunderstanding this, but it certainly seems suspicious at first glance and is what prompted this bug report.

[logs.zip](https://github.com/christkv/mongodb-core/files/63192/logs.zip)

Even if this is a bug, it doesn't really explain the reason that the socket is only sometimes closed, and only when connecting to a replica set, but having a reliable pool is important to us.

Thinking more about it, the assumption that a replica set connection is what causes it may be wrong.  I have tried many times using a connection to only our primary server at MongoLab (i.e. no replica set information) and never gotten it to fail.  But, it's certainly possible that it just fails so much less often in that configuration that I have not yet seen it.

**Comment by christkv** [comment]
Yeah that connection pool works as designed. There is plans to experiment with with other pool designs in the near future but nothing in the next 3 months at least. Changing it would require an extensive refactoring and would change the behavior of the driver at several levels as authentication information would have to be managed differently than today.

I suspect the reason it socketTimeoutMS and connectTimeoutMS needs to be adjusted due to some latency issues.

A lot of people have recently commented on problems with Mongolab and timeouts. Here is a checklist to try out.

1. Ensure replicaset configuration on the replicaset contains only hosts that are reachable by the driver. All members MUST be reachable by the driver.
2. Set socketTimeoutMS and connectTimeoutMS to 0 so it defaults to OS level timeout and see if the problem goes away. If it does experiment with the right values you expect.
3. Add listeners to the db.serverConfig on the `joined` and `left` events to log how the server sees the topology.

I'll be out for the rest of the year and offline most of the time but will revisit once I get back in january.

**Comment by mkw** [comment]
Thanks very much for the help.  I had already set socketTimeoutMS to 0, and from the logs, I don't think that changing connectTimeoutMS from 30s to 0 will change anything, but I'll try that, too.  I'm also going to investigate setting the socketTimeoutMS to 300s on Linux (and 600s on OS X), as I just learned that the MongoDB docs specify that values over that will be ignored [here](https://docs.mongodb.org/v3.0/faq/diagnostics/).

Note that I just spotted the error locally (i.e. connected to 127.0.0.1) where I have a 1-server pseudo-"replica set" running.  I was running in the debugger, so it's likely that halting node contributed to it, but it's the first time that I can confirm it happened running against a host not hosted by MongoLab.

Again, I appreciate the help, and if I learn anything more, I'll post it here.

**Comment by Martii** [comment]
@mkw 

> will be ignored

I am reading this as being capped at those values. Thanks for the linkage too. :)

**Comment by christkv** [comment]
@mkw if you can reproduce on localhost, please add reproducible steps.

**Comment by chrisckchang** [comment]
@mkw @Martii @christkv 

We have reliably reproduced the issue and are in the process of opening a ticket with MongoDB to better understand the behavior behind this issue. 

From our experimenting, we have had success eliminating these errors by increasing the connectTimeoutMS setting to a very large value such as 60*1000. We recommend the following configuration as a temporary workaround while we try to understand more about the driver behavior:

```
MongoClient.connect("mongodb://<dbuser>:<dbpassword>@host1:port1,host2:port2/<dbname>?replicaSet=replicaSetName", {
  replset: {
    socketOptions: {
      connectTimeoutMS: 60*1000
    }
  }
}, function(err, db) {
});
```

Note that if you are connecting to a replica set, the "server" level options will not be used. Use "replset" instead. Also, I suspect that if you are running very long-running operations against your database deployment, you may need to increase your connectTimeoutMS option to an even larger value.

**Comment by Martii** [comment]
@chrisckchang 

> if you are connecting to a replica set, the "server" level socketOptions will not be used.

Hmmm so there's currently no documented `autoReconnect` for that then at http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html ... I wonder where that went then?

It's probably not really hurting our VPS at the moment... just passing around a bigger object which is what I thought I was getting rid of in dev earlier today. Thanks for the tip... will throw it back onto the TODO pile.

**Comment by christkv** [comment]
@Martii autoReconnect has no meaning in a replicaset setting only in a single server one.

@chrisckchang you should set both connectTimeoutMS as well as socketTimeoutMS to high values if you know you have long running operations. I've added a FAQ to the docs, link below.

http://mongodb.github.io/node-mongodb-native/2.1/reference/faq/

**Comment by mkw** [comment]
@christkv I only saw the error once on localhost, and it was while I was debugging something else via the debugger.  I suspect it's a timing thing, given that debugger pauses so radically change timings, but I've no idea what exactly caused it, and I've run that same code 100's, if not 1000's of times locally and never seen the error before or since.

**Comment by mkw** [comment]
@chrisckchang I'm still trying to figure out exactly what does cause it, but increasing connectTimeoutMS has no effect.  I've tried values well over 10 minutes.  My best guess right now is that there is a bug in MongoDB itself, and MongoDB is closing the connection.  We had an aggregation that got oddly slow: it started taking 2+ minutes as our data grew, but when I broke it up into 6 chunks, each chunk finished in ~100ms.  When the aggregation that was slow was running, a very simple "give me everything from this small (<200KB) collection" operation seemed to block until the aggregation was finished.  Once I broke the large aggregation into chunks to make it fast, the problem went away.

**Comment by christkv** [comment]
@mkw try out 2.0.53 or 2.1.2 I think I fixed this particular issue and there was a bug or well unintentional side effect of an architectural decision.

**Comment by mkw** [comment]
@christkv Thanks for the Christmas present -- not only does that update fix the performance issue that I described, I'm no longer able to reproduce the socket closure, and I think that it may have sped up several other batch jobs at the same time.

I'm clicking the "Close and comment" button because I believe this is now, effectively, fixed.  But, if you want to use the issue to track design changes to the connection pool, it would not bother me if you reopened it.

**Comment by elephantjim** [comment]
:gift: This fixed our problem too.  Thanks!

FWIW, it isn't ideal.  In our application we have many workers, each with one connection to the database.  Adding one more connection to the pool for monitoring isn't much when you have 100 connections already there, but for us it means doubling the number of connections to the database.

**Comment by christkv** [comment]
@elephantjim there is no other fix possible until MongoDB itself goes async. As long as there is a single thread per socket on MongoDB using a non-exclusive socket will always run into the slow train problem if there are enough slow queries.
