### ISSUE TITLE
Unrecognized pipeline stage name: '$lookup'

### ISSUE THREAD

**Issue by niftylettuce** [christkv/mongodb-core#67]

**Comment by niftylettuce** [comment]
Doesn't seem to have $lookup support if you do `.aggregate([ { $match: {} }, { $lookup: {} ...`

**Comment by vkarpov15** [comment]
See my comments in https://github.com/Automattic/mongoose/issues/3682#issuecomment-165204186. Can you double check your mongod version?

**Comment by divined** [comment]
Uncaught PHP Exception MongoDB\\Driver\\Exception\\RuntimeException: "exception: Unrecognized pipeline stage name: '$lookup'"

> db.version()
3.2.17
