### ISSUE TITLE
Improving pool performance for query interleaving better than round robin

### ISSUE THREAD

**Issue by owenallenaz** [christkv/mongodb-core#69]
One thing we've noticed in our application is that long queries will cause back-up in pool members, even when there are other pools members available to service the request. From looking into the code, I can see that the pool is a round-robin approach. When a new command is issued it is put into a the next socket, even if that socket is busy at the moment, and there are other sockets which may not be busy.

I believe we could really improve throughput and multi-query interleaving if we did one of the two following things:

1. Keep track of the number of queries that each pool member has queued up, and assign the next query to the pool member with the lowest number of in-progress queries. I believe this could be done fairly easily without having to refactor too much code. The downside of this approach is that it's still not as optimal as a queue-worker system because a query could still get backed up behind a slow one, and a socket could come available before it's been serviced, leaving pool members not-working and queries still to be ran.

2. Switch to a queue-worker system for the pool members. Basically, each command gets put into a queue, if there is a pool member available, it will service the request. When a pool member finishes a command, it grabs the next command off the queue and services it. The advantage of this approach is that it should ensure that all pool members are working at all times. New faster queries will still make it through. Slower queries won't stall faster queries unless you have more slow queries that total pool members. This approach could require a fair bit of refactoring to make it possible.

I have some time over the Christmas break to play around with it. I just don't want to start on a pull request unless it's something you would consider at some point.

**Comment by christkv** [comment]
1. Would just stall the problem for a little bit longer but the end result would be the same me thinks.
2. This could work but it would introduce a process.nextTick loop that when there are no messages in the queue to execute possibly causing a fair bit of CPU usage as there would be a lot of constant process.nextTick calls.

I'm not planning to change anything in the next 3-6 months but if you do pursue any of them I would happy to at least discuss them and what experiences you made them and if any of them prove fruitful might consider them for mongodb-core 2.0 in 2016.

**Comment by owenallenaz** [comment]
1. Agreed.

2. I wouldn't want to do this if we had to poll for available jobs. I'm pretty sure it wouldn't be necessary if we run jobs on workers both when a worker finishes (grabbing the next job off the queue), or when a command is issued (checking for available workers) and running it if a worker is available. Hopefully in the next week I should be able to work something up.

**Comment by christkv** [comment]
I'm not sure you need more than a single dispatcher as only one piece of javascript can run at any one time. When you see how the driver works you can see that there is a single reader for each connection that takes care of all incoming messages as the dispatcher would just register the callback.

That said you would need to ensure one of the sockets where completely reservable if needed to ensure the replicaset could have special access to a non contended socket for monitoring.

**Comment by owenallenaz** [comment]
From looking at the existing code, you recently a monitoring socket based on sockets + 1. My question is, if I've decided on a socket pool size of 5 how does this relate to things like primary and secondary? Lets say I have a poolSize of 5, does it open 5 + 1 per server in my replSet?

**Comment by christkv** [comment]
yes that is correct, the last connection is exclusively reserved for replicaset monitoring and discovery so no long running operations can ever cause the monitoring and discovery to stall.

**Comment by owenallenaz** [comment]
I've created a pull request at #71 . Let me know your thoughts here or in the pull.

**Comment by christkv** [comment]
Hi owen, I'll try to review this next week as I'm stuck with some other issues around benchmarking the driver at the moment for an internal project. This will not make it in the 1.x branch of mongodb-core, however my plan is for the 2.x branch to contain this type of architectural change as well as a growing connection pool.

**Comment by bompus** [comment]
+1 - This would fix my issue where fast queries are getting stacked up behind slow queries on a single connection in the pool.

**Comment by christkv** [comment]
Hi I've scheduled reworking the mongodb-core to be a worker queue model for next quarter as a stretch goal. This would include the 3 following refactorings.

- Refactor pool to allow to grow and shrink
- Refactor authentication to support pool growth and shrink.
- Refactor code to be worker queue based (I might or might not take the code from here but I'm sure to use it as a reference for the work).

**Comment by owenallenaz** [comment]
It's kind of a shame to have to wait 5 months till the end of Q2 for a pull request that's working. If there are issues with the pull, then I'm happy to improve them or change them. In our environment, one query takes 5s and the whole application grinds to a halt, I can't imagine we are the only people having this problem. Even if you set a poolSize of 20, an average page will do more than 20 queries, so it has a 100% chance of getting stuck behind the slow query from another part of the app because of the round-robin.

The very fact that you had to create a special monitor socket is evidence of this issue. If you had a as-needed pool you would never need a special socket, because there will nearly always be one socket open, as my guess is that the monitor socket was stuck behind the slow query (even while other sockets lay dormant).

**Comment by christkv** [comment]
We want to do the refactoring once meaning it needs to be planned as part of our work commitments. On the good side Q1 starts feb 1st so it's max 3 months, depending on what other issues are out. I do intend sooner rather than later so hopefully not at the end of the quarter.

Unfortunately the work queue does not solve the issue of monitoring as the pool still has an upper limit and once hit it would still be subject to the slow train if the number of slow ops >= max number of connections in the pool causing the same issues as before we had a dedicated connection.

If this is critical for you right now I think it's fine if you fork until the refactoring is done as any changes will be transparent to the higher level driver.

**Comment by christkv** [comment]
Checkout mongodb-core 1.3.0 that includes a worker queue as well as growing/shrinking pool. I've some other small things that need to be cleared but should be out in 2.1.5 once they are ready.

**Comment by christkv** [comment]
2.1.5 is out with new worker pool and also growing/shrinking connection pool size.
