### ISSUE TITLE
batched raw mode finds sometimes fail

### ISSUE THREAD

**Issue by andrasq** [christkv/mongodb-core#72]
batched raw mode finds sometimes lose the currentState.cursorId, and return just the
firstBatch of matching documents with a metadata object appended.  The metadata object
is the internal `doc` returned to `_getmore` (ie, an object with fields `ok` and `cursor`,
cursor containing fields `nextBatch`, `id` and `ns`)

I was unable to identify the cause, a simple test that opens and uses a connection
does not reproduce; the breaking app makes multiple connections and calls.
raw:false mode does  not exhibit the problem.

The below patch seems to work.

tested with mongodb-V2.1.3 and mongodb-core-V1.2.31, mongodb-3.2, node-v0.10.41

```
--- a/lib/cursor.js
+++ b/lib/cursor.js
@@ -691,16 +691,28 @@ var nextFunction = function(self, callback) {
 
       // Check if connection is dead and return if not possible to
       // execute a getmore on this connection
       if(isConnectionDead(self, callback)) return;
 
       // Execute the next get more
       self._getmore(function(err, doc) {
         if(err) return handleCallback(callback, err);
+
+        // AR: sometimes raw mode loses the currentState.cursorId causing the second and subsequent batches
+        // to never be fetched.  This happens only on nextBatch, never on the firstBatch returned.
+        // This kludgy patch fixes up the cursorId so the entire dataset is returned.
+        if (self.cursorState.cmd.raw && doc.length == 1 && doc[0] && doc[0].ok === 1 && doc[0].cursor &&
+            Object.keys(doc[0]).length == 2 && doc[0].cursor.nextBatch && typeof doc[0].cursor.id === 'number')
+        {
+          self.cursorState.cursorId = Long.fromNumber(doc[0].cursor.id);
+          self.cursorState.documents = doc[0].cursor.nextBatch;
+          self.cursorState.cursorIndex = 0;
+        }
+
         if(self.cursorState.documents.length == 0
           && Long.ZERO.equals(self.cursorState.cursorId) && !self.cmd.tailable) {
             self.cursorState.dead = true;
             // Finished iterating over the cursor
             return setCursorDeadAndNotified(self, callback);
           }
 
         // Tailable cursor getMore result, notify owner about it
```

**Comment by christkv** [comment]
the problem was more subtle and realated to the MongoDB 3.2 wire protocol, can you confirm this commit fixes this issue for you. It's bundled with some other things but just ignore those. relevant fix is in 3_2_support.js and then I took you code example and added it as a test.

**Comment by andrasq** [comment]
the revised mongodb-core breaks mongoClient.connect:
```
% cat << EOF | node
? mongoClient = require('mongodb').MongoClient;
? mongoClient.connect("mongodb://localhost/test", {}, function(err, db) {
?   if (err) throw err;
?   db.close();
? });
? ^D
/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/server.js:236
        process.nextTick(function() { throw err; })
                                            ^
Error: One, two, tree or four arguments required - [object] or [object, boolean] or [object, boolean, boolean] or [object, boolean, boolean, boolean]
    at Query.toBin (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/connection/commands.js:143:25)
    at executeSingleOperation (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/topologies/server.js:786:28)
    at Server.command (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/topologies/server.js:883:12)
    at /home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/topologies/server.js:371:12
    at /home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/topologies/server.js:359:18
    at ScramSHA1.reauthenticate (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/auth/scram.js:303:25)
    at applyAuthentications (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/topologies/server.js:355:36)
    at null.<anonymous> (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/topologies/server.js:367:5)
    at g (events.js:180:16)
    at emit (events.js:95:17)
```

The error is coming from connection.write in toplogies/server.js executeSingleOperation,
but the command sent is the same as before.

**Comment by christkv** [comment]
do you have bson-ext installed ?

**Comment by christkv** [comment]
remove bson-ext it's not really supported in the 2.x series of drivers and give no performance benefit.

**Comment by andrasq** [comment]
thanks for the quick response!

it wasn't bson-ext, it was an older version of bson that got dragged in alongside
the other app modules with `npm install .`  With the right bson, connect works,
and NODE-642 (even multiple of batchSize data items returns error) is fixed.

Unfortunately, the #72 batched raw mode just-first-batch-plus-metadata glitch is still there.
(Possibly related, this same raw mode cursor returns decoded js objects not Buffers
when called with cursor.toArray())

**Comment by christkv** [comment]
Can you give a simple example of the query and data being executed. I can then try to hammer it and see what happens. it's very strange.

**Comment by andrasq** [comment]
the test inserts 10001 items (or 101) of the form `{ unique: i, random: Math.random()}`
into an empty collection, then calls the service that does a `find({})`.  Batch size is set to 50.
The problem is seen in a unit test that inserts in the test, then calls a service that does a find({}),
then a toArray(), and returns the results, 51 documents, 50 data and 1 metadata.
The unit test can read back all the data just fine, it's the service that fails.

The service reads a few metadata collections before fetching the data.
I'll try to trace the exact sequence of calls.

**Comment by christkv** [comment]
ok will await investigation

**Comment by andrasq** [comment]
captured the find call in transit, when called directly and when called from the app.
Directly, the callback `raw` attribute is set.  From the app, it is not.  The commands
being sent are indentical, however.

Tace of the calls to WireProtocol.prototype.command and to server.js:messageHandler,
direct:
```
AR: wire command { find: 'kdsTests.largeBSONfind',
  limit: 0,
  skip: 0,
  query: {},
  raw: true,
  slaveOk: true,
  readPreference: { preference: 'primary', tags: undefined, options: undefined },
  batchSize: 50 } { cursorId: null,
  cmd: 
   { find: 'kdsTests.largeBSONfind',
     limit: 0,
     skip: 0,
     query: {},
     raw: true,
     slaveOk: true,
     readPreference: { preference: 'primary', tags: undefined, options: undefined },
     batchSize: 50 },
  documents: [],
  cursorIndex: 0,
  dead: false,
  killed: false,
  init: true,
  notified: false,
  limit: 0,
  skip: 0,
  batchSize: 50,
  currentLimit: 0,
  transforms: undefined } Error
  at [object Object].WireProtocol.command (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/wireprotocol/3_2_support.js:224:51)
  at nextFunction (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/cursor.js:607:52)
  at [object Object].Cursor.next [as _next] (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/cursor.js:785:3)
  at fetchDocs (/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/cursor.js:847:10)
  at toArray (/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/cursor.js:874:3)
  at [object Object].Cursor.toArray (/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/cursor.js:827:44)
...

AR: got message 28 true { callbacks: { '28': { [Function] raw: true, documentsReturnedIn: 'firstBatch' } },
  id: 3,
  type: 'server' }
```

from the app (broken):
```
AR: wire command { find: 'kdsTests.largeBSONfind',
  limit: 0,
  skip: 0,
  query: {},
  raw: true,
  slaveOk: true,
  readPreference: { preference: 'primary', tags: undefined, options: undefined },
  batchSize: 50 } { cursorId: null,
  cmd: 
   { find: 'kdsTests.largeBSONfind',
     limit: 0,
     skip: 0,
     query: {},
     raw: true,
     slaveOk: true,
     readPreference: { preference: 'primary', tags: undefined, options: undefined },
     batchSize: 50 },
  documents: [],
  cursorIndex: 0,
  dead: false,
  killed: false,
  init: true,
  notified: false,
  limit: 0,
  skip: 0,
  batchSize: 50,
  currentLimit: 0,
  transforms: undefined } Error
  at [object Object].WireProtocol.command (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/wireprotocol/3_2_support.js:224:51)
  at nextFunction (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/cursor.js:607:52)
  at [object Object].Cursor.next [as _next] (/home/andras/work/src/kds.git/node_modules-new/mongodb-core/lib/cursor.js:785:3)
  at fetchDocs (/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/cursor.js:847:10)
  at toArray (/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/cursor.js:874:3)
  at [object Object].Cursor.toArray (/home/andras/work/src/kds.git/node_modules-new/mongodb/lib/cursor.js:827:44)
...

AR: got message 28 undefined { callbacks: { '28': { [Function] domain: [Object] } },
  id: 1,
  type: 'server' }
```

Still tracing the flow otherwise.

**Comment by andrasq** [comment]
So server.js Callbacks.prototype.register calls bindToDomain which calls process.domain.bind,
which loses the `raw` attribute from the callback.  When bindToDomain returns the callback as is,
`raw` is preserved.

**Comment by owenallenaz** [comment]
My pull request for the pool connection issues fixes the issue he refers to above. bindToDomain doesn't copy across fn properties applied to the callback. My pull request is sufficiently different that it might not be easily integrated but I remember correcting this issue.

**Comment by christkv** [comment]
let me know if this resolves the issue

**Comment by andrasq** [comment]
success!  The bindToCurrentDomain change (commit 5ff431b5f63fb9f6fd4c263505e6cacc40180560) fixes the problem I was seeing

**Comment by andrasq** [comment]
any ETA for when this fix will make it into node-mongodb-native?

**Comment by christkv** [comment]
hopefully later this week with a 2.1.5 release
