### ISSUE TITLE
TypeError: Cannot read property 'Kerberos' of undefined

### ISSUE THREAD

**Issue by fourpixels** [christkv/mongodb-core#75]
Hi there,
I just started a really new project, right from blank. I've installed mongoose, which lead to installing mongodb and mongodb-core. But right when I start the server (with no configuration at all), I get this error message in the console:

`[TypeError: Cannot read property 'Kerberos' of undefined]`

I've tracked it down to `mongodb-core\lib\auth\sspi.js`, around line 31:

```js
try {
  Kerberos = require_optional('kerberos').Kerberos
  // Authentication process for Mongo
  MongoAuthProcess = require_optional('kerberos').processes.MongoAuthProcess
} catch(err) {
  console.dir(err)
}
```

To be honest, I've never used Kerberos, and I haven't configured to do so. It might be because of `mongoose` or other kind of library (that they are calling `sspi` - haven't checked the stack at all), but it seems a bit weird to me to use `console.dir` for printing out the result of a `try-catch`. Maybe use debug or some other kind of framework?

I would love to see how to remove this message from my console :) Thanks!

p.s. 

```json
"mongoose": "^4.4.2" // main package.json
"mongodb": "2.1.5" // mongoose package.json
"mongodb-core": "1.3.0" // mongodb package.json
```

**Comment by christkv** [comment]
fixed in mongodb 2.1.6
