### ISSUE TITLE
Cursor's memory leak!

### ISSUE THREAD

**Issue by zensh** [christkv/mongodb-core#77]
http://stackoverflow.com/questions/27392679/memory-leaks-when-iterating-over-mongo-data-stream-using-nodejs

Consumed documents in `cursor.cursorState.documents` will not be removed!

Demo code:
```js
thunk(function *() {
  yield [mongo.clientReady, mongo.oplogClientReady]
  yield thunk.delay(100)

  let oplog = mongo.oplogClient.db.collection('oplog.rs')
  let cursor = oplog.find()
    .addCursorFlag('tailable', true)
    .addCursorFlag('noCursorTimeout', true)
    .addCursorFlag('awaitData', true)
    .addCursorFlag('exhaust', true)

  let count = 0
  while (true) {
    let log = yield cursor.next()
    console.log(count++, log.ns, log.ts, cursor.cursorState.documents.length)
  }
})(ilog.error)
```

Result:
```sh
528018 'talksync.messages' Timestamp { _bsontype: 'Timestamp', low_: 9065, high_: 1456264568 } 528020
528019 'talksync.messages' Timestamp { _bsontype: 'Timestamp', low_: 9066, high_: 1456264568 } 528020

<--- Last few GCs --->

  202118 ms: Scavenge 1401.6 (1457.9) -> 1401.6 (1457.9) MB, 5.5 / 0 ms (+ 2.7 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  203039 ms: Mark-sweep 1401.6 (1457.9) -> 1401.5 (1457.9) MB, 920.3 / 0 ms (+ 4.0 ms in 2 steps since start of marking, biggest step 2.7 ms) [last resort gc].
  203957 ms: Mark-sweep 1401.5 (1457.9) -> 1401.2 (1457.9) MB, 918.7 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3fab912b4629 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/Users/zensh/git/teambition/databus/node_modules/mongoose/node_modules/bson/lib/bson/parser/deserializer.js:~37] [pc=0x1e082ac08460] (this=0x3fab912041b9 <undefined>,buffer=0x3fab912885b9 <an Uint8Array with map 0xd5818104d09>,index=73,options=0x3fab91288609 <an Object with map 0xd58181bb2c9>,isArray=0x3fab91204251 <false>)
    2: /* anonymous */(aka...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    3511 abort      node
```

**Comment by christkv** [comment]
Do not use exhaust under any circumstances as it will make mongod send all documents at once causing your massive documents array. I plan to remove support for exhaust soon as it causes a lot of confusions like this.

**Comment by zensh** [comment]
Thank you. It work well when exhaust closed.
Another problem is that I need to handle "No more documents in tailed cursor" Error and restart a new cursor to read(wait) oplog. Is here some way to keep the cursor alive? Cost of restart cursor is expensive.

**Comment by christkv** [comment]
If you are using mongodb 3.2 you can use the option maxAwaitTimeMS on the cursor in the 2.1.x series of drivers to have it wait for x MS before closing alleviating the problem. If you have to reopen the cursor you should set the **oplogReplay** flag as well as issue the query to the oplog with your last recorded oplog timestamp to speed up reconnection.

**Comment by zensh** [comment]
Thank you very much!

**Comment by christkv** [comment]
no problem best of luck :)

**Comment by eshujiushiwo** [comment]
HI @christkv 
Thanks for the reply.
I have a question about this case.
 When using tailable cursor , we wanna trace and monitor the change of this collection.
Once there is no data writing into the collection,the cursor should waiting for the new data.
And  MongoDB will not kill the cursor , will driver kill the cursor itself?
when using tailable cursor with php or golang, it might wait for the new data.

Thanks for ur help.
