### ISSUE TITLE
Slow Query inside docker container

### ISSUE THREAD

**Issue by allancarvalho** [christkv/mongodb-core#82]
Hello, 

I'm doing a query (find) inside mongo that in my computer(osx) takes 20ms.
But inside a docker container the same query takes 80ms.

I don`t know why, but it happens after version mongodb-core@1.1.32

In version mongodb-core@1.1.32 the query takes same time in docker or in my machine
But in mongodb-core@1.2.0 the problem happens.

My node version is v4.2.3

Any ideas?

Thanks

**Comment by christkv** [comment]
no idea, feel free to test out the 1.3 branch instead which is the one underpinning the 2.1.x series of the driver.

**Comment by christkv** [comment]
no feedback, closing

**Comment by allancarvalho** [comment]
Sorry. 
I have tested with newest versions, but the problem continues.

My big doubt is the difference with my machine, and inside a docker container.

I think that something happens when it will unserialize the data. Some bin is missing in docker container.

Any ideas how to debug it ?
