### ISSUE TITLE
cursorNotFound flag always false

### ISSUE THREAD

**Issue by xgfd** [christkv/mongodb-core#83]
At [line 448 of lib/connection/commands.js](https://github.com/christkv/mongodb-core/blob/master/lib/connection/commands.js#L448), since `CURSOR_NOT_FOUND` is set to `0`, `this.cursorNotFound` is always `false`. Is that an intended behaviour (reserved for future use)?

**Comment by christkv** [comment]
No you are right the value should actually be 1. In practice this flag is legacy as an actual error message is returned from the server when no cursor is found.

**Comment by xgfd** [comment]
Thanks Chris. 
Something off topic, I figured out the encoding of normal commands, queries etc. from your source, however it seems some internal commands (e.g. whatsmyuri) have a different scheme? Any chance it's documented somewhere? Thanks a lot in advance.
