### ISSUE TITLE
Somewhere between V1.2.30 and V1.3.5, the number of connections seems to grow without bound

### ISSUE THREAD

**Issue by NigelKibodeaux** [christkv/mongodb-core#86]
Sorry for the vague bug report. We had to roll back to 1.2.30 after our number of connections grew to the thousands with 1.3.5.

**Comment by christkv** [comment]
I'm having problems recreating the issue so I would appreciate any help you can have in the events that cause this to happen and what version of node, os, mongodb etc.

**Comment by NigelKibodeaux** [comment]
Sure, we're on 

- node: 5.6.0
- mongodb: 2.6.11
- OS: debian jessie

**Comment by christkv** [comment]
Can you recreate it with a small script and describe the replica set that causes it ? This way I can hopefully track it down faster and get a fix out

**Comment by martincad** [comment]
Found exactly the same issue. Our app starting to work slower and slower. After digging we found the mongodb connections grew from and avg of 140 to more than 11K. On our last deploy, the mongodb driver got updated from 2.1.7 to 2.1.8.

We just rolled it back to 2.1.7 and seems everything went back to normal.

Not easy to recreate outside the whole app.

Just in case, with 2.1.8 we found plenty of "error: [TypeError: Cannot read property 'calculateObjectSize' of null]" errors.

**Comment by christkv** [comment]
Can you provide a full stack trace ? Do you do bulk operations ?

**Comment by NigelKibodeaux** [comment]
We experienced in our staging environment in which we have a primary and secondary running on separate m1 small instances in AWS. Hopefully that helps.

**Comment by martincad** [comment]
@christkv No, its just a regular Insert. Dont have a traceback here, will post it when I have it.

Mongo 2.6.11 is running with a master and two replicas.

**Comment by christkv** [comment]
Collection.insert or collection.insertMany. Multiple docs inserted at the same time ?

**Comment by martincad** [comment]
Collection.insert

**Comment by christkv** [comment]
If you do have the possibility to do a quick test with 1.3.6 it's just been released. I think I have found the issue and it's caused by a possible race condition.

**Comment by martincad** [comment]
@christkv Do you have the possibility to generate a mongodb npm module version 2.1.9 including this mongodb-core fix ?

Could not reproduce it on our staging environment, so I need to try on the production one, but need the mongodb package

**Comment by christkv** [comment]
2.1.9 is in NPM but not marked stable or latest

**Comment by bompus** [comment]
@christkv Is it possible to publish and mark 2.1.10 as latest? Apart from connection growth, hoping it might solve a possible issue where the module gets stuck in a "no primary server" state forever, even when a primary comes back online.

**Comment by christkv** [comment]
@bompus you saying that happens in 2.1.9 as well ?

**Comment by bompus** [comment]
On 2.1.7 , but I'm not 100% positive. Reproducing was difficult last time I tried. Hoping 2.1.9 or 10 help.

**Comment by wavo89** [comment]
Occurring for me on 2.1.9, as well as earlier versions. Occurs overnight after idling for 6 or so hours.
It also used to occur more frequently when I had a syntax error in my code that was able to be compiled. At that point, it occurred in like 3 hour long fits, where as soon as the server rebooted it would begin accruing connection (without any other triggers), then crash after 10 minutes @ 11,000 connections.
After fixing that, I still experience this issue but it seems to occur without any trigger.

**Comment by christkv** [comment]
can you verify if this happens on 2.1.11.

**Comment by wavo89** [comment]
The issue is gone for me as of now- I had to make sure that I used the most up to date Parse dependency as well.

**Comment by christkv** [comment]
close as resolved.

**Comment by martincad** [comment]
**Note:** (for those who experienced yesterday (07-06-2016) / today some connection leakage), 

> npm install mongodb

was installing the buggy version 2.1.8 instead of 2.1.18 as mention here:
https://jira.mongodb.org/browse/NODE-744

The issue is now fixed (we had a bad time yesterday trying to understand why our connections grew from 100 to 30.000)
