### ISSUE TITLE
Endlessly reconnecting to database since 1.3.19 update

### ISSUE THREAD

**Issue by leleuj** [christkv/mongodb-core#97]
I just upgraded to mongodb-core 1.3.19 instead of 1.3.18 (+ mongodb 2.1.15) on Mac OS X and the driver is endlessly reconnecting to the database.

My code:

```
MongoClient.connect('http://localhost:27017/test', { poolSize: 10, autoReconnect: true, connectTimeoutMS: 500, socketTimeoutMS: 1000 }, function(err, db) {
    if (err) {
        logger.error(new Error('Cannot connect to Mongo -> stop'));
        process.exit(-1);
    } else {
        logger.info("Connected to test database");
        db.on('close', function() {
            logger.warn('Connection lost to database');
            dbOk = false;
        });
        db.on('reconnect', function() {
            logger.warn('Reconnecting to database');
            dbOk = true;
        });
        entries = db.collection('entries');
        dbOk = true;
    }
});
```

Previously, the driver connected to the database and that was all, but now my logs are full of "Reconnecting to database"...

Is there something wrong with the driver v1.3.19?

**Comment by christkv** [comment]
this is the expected behavior when there is no operations flowing on the db 1.3.18 had a bug that caused the server to ismaster call itself when not part of a replicaset or mongos topology.

**Comment by leleuj** [comment]
There was a bug and you fixed it, it sounds perfectly normal. Though, we realized something has changed when doing performance tests. We have very good performance (with 1.3.18) and now with the 1.3.19 version, we have very poor performance.

We do a simple search (using Apache ab) on an indexed field through an url exposed via express (/login/xxx):

```
entries.find({"login": login}, {
    timeout: true,
    maxTimeMS: 1000,
    maxAwaitTimeMS: 1000,
    limit: 2,
    readPreference: ReadPreference.SECONDARY_PREFERRED
}).toArray(function (err, docs) {
    if (err) {
        callback(err, null);
    } else {
        callback(null, docs);
    }
});
```

Did you do perform some performance tests on this new version?

**Comment by christkv** [comment]
well if your sockets are timing out constantly that would explain the drop in performance as the driver is constantly reconnecting. I would suggest setting a higher socket timeout

**Comment by leleuj** [comment]
I guess you refer to `maxAwaitTimeMS`: the problem is that I have performance issues on my validation platform as well as on my local computer where obviously, there shouldn't be any "socket timeout" issue.

**Comment by christkv** [comment]
No I'm talking about the socketTimeoutMS: 1000 in the connection string. if you have something like that its very conceivable that it would happen. each reconnect would cause a performance drop as you cycle the connection pool. socketTimeoutMS should be longer than the longest running op or the longest dead time your application experiences to avoid this.

http://mongodb.github.io/node-mongodb-native/2.1/reference/faq/

**Comment by leleuj** [comment]
Indeed, I removed the `socketTimeoutMS` (so it defaults to 30 seconds) and things are working correctly now. Thanks for your help.
